### ISSUE TITLE
feature request: fail on user-defined minimum coverage level

### ISSUE THREAD

**Issue by isaacs** [bcoe/nyc#105]
It'd be cool to specify (via env probably, so as to not mess with args?) a minimum level of statement/branch coverage, below which it's considered a failure.

Coveralls provides this, so the travis/coveralls wire-up I've got for node-tap meets my needs for PRs and such.  But it'd be good to surface this to a potential contributor ahead of time.  Like, "Yes, your tests pass, but you dropped the coverage below acceptable amounts, so fix that first."

**Comment by bcoe** [comment]
In the bin, there's a way to do this:

`https://github.com/bcoe/nyc/blob/master/bin/nyc.js#L99`

But we just hook into the `istanbul` CLI; It would be cool to see if they expose this behavior through their API.
