### ISSUE TITLE
`--all` appears to be broken in 5.1.0

### ISSUE THREAD

**Issue by Lalem001** [bcoe/nyc#120]
In `nyc@5.1.0`, I am getting the following error whenever `--all` is used:

```bash
user$nyc --all ava 'test/**/*.js'
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/user/project/.nyc_output/7910.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at NYC.writeCoverageFile (/Users/user/project/node_modules/nyc/index.js:259:6)
    at NYC.addAllFiles (/Users/user/project/node_modules/nyc/index.js:171:8)
    at Object.<anonymous> (/Users/user/project/node_modules/nyc/bin/nyc.js:122:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

Not sure where to start looking on this issue.

**Comment by bcoe** [comment]
@Lalem001 do things work on `5.0.1`?

**Comment by Lalem001** [comment]
@bcoe yes. 

I just experimented a bit and removing `writeCoverageFile` from `addAllFiles` stops the error, but I don't know yet if that changes the final output.

**Comment by bcoe** [comment]
CC: @jamestalmage any thoughts on this?

**Comment by Lalem001** [comment]
Final output is affected, of course, without `writeCoverageFile`. Will keep experimenting.

**Comment by jamestalmage** [comment]
Looks like it needs `nyc._createDatastoreDirectories()` [here](https://github.com/bcoe/nyc/blob/master/bin/nyc.js#L121).

That used to create the cache and temp directories, but now it is back to just creating temp. So the name can probably be returned to `createTempDirectory()`

Needs further investigation, but I suspect #112 is the reason this wasn't caught by our tests.

**Comment by Lalem001** [comment]
From what I can tell the issue is caused by a missing `.nyc_output` directory.

If I disable `NYC.cleanup`, and manually create the directory, `--all` works fine.

**Comment by jamestalmage** [comment]
@Lalem001 - you are correct - see my comment above. You would not want to disable `cleanup`, but rather make sure the datastore directory gets created.

**Comment by Lalem001** [comment]
@jamestalmage Disabling cleanup was just a step to figuring out the issue.

**Comment by bcoe** [comment]
@Lalem001, @jamestalmage cool -- this is why we release to a `next` branch first. Let's get a test around this behavior before we push `5.1.1` to `next`; perhaps we can just solve the cleanup ticket like @jamestalmage suggests.

**Comment by Lalem001** [comment]
`_createDatastoreDirectories` is called on `new NYC`. `nyc.cleanup` is called afterwards by the bin. To then call `_createDatastoreDirectories` again seems a bit redundant.

Perhaps we could add a cleanup option to NYC and cleanup before `_createDatastoreDirectories`?

**Comment by jamestalmage** [comment]
Or, let's create a `reset()` function that is:

```js
NYC.prototype.reset = function() {
  this.cleanup();
  this._createDatastoreDirectories();
}
```

Then, in the CLI, only use `reset()`, and stop calling `_createDatastoreDirectories()` needlessly in every fork. That should give us a minor performance boost.

Feel free to come up with a better name than `reset`. :smile:

**Comment by Lalem001** [comment]
@jamestalmage `provision`?

**Comment by jamestalmage** [comment]
> `provision`?

I don't know. I think I might like `reset` better (though I'm still not thrilled with either).

Let's see if @novemberborn or @bcoe come up with anything.

**Comment by bcoe** [comment]
my vote would be for `cleanup`, let's get a pull for this in a branch that also resets state between tests -- @jamestalmage did you want to tackle this, or @Lalem001?

**Comment by jamestalmage** [comment]
So just add directory creation to the end end of the existing `cleanup` function?

**Comment by novemberborn** [comment]
> So just add directory creation to the end end of the existing cleanup function?

Shouldn't `cleanup`, you know, clean up? Maybe the `NYC` constructor shouldn't create the directories. `bin/nyc` should, and anything else that calls `NYC` directly.

**Comment by jamestalmage** [comment]
> Shouldn't cleanup, you know, clean up?

That was my thought with naming it `reset()` it seemed more appropriate (though definitely not the perfect name).

**Comment by jamestalmage** [comment]
See #121. I just named it `reset`. Happy to change it if someone has better ideas.
