### ISSUE TITLE
yarsay tests fail when running with --cache flag

### ISSUE THREAD

**Issue by bcoe** [bcoe/nyc#124]
@jamestalmage I know this is something that was fixed at one point, but I can't seem to get the `lcov` report working if `--cache` is set for `yarsay`.

```sh
Benjamins-MacBook-Pro:yarsay benjamincoe$ nyc report --reporter=lcov
/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:241
            text = structuredText[startLine].text;
                                            ^

TypeError: Cannot read property 'text' of undefined
    at /Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:241:45
    at Array.forEach (native)
    at annotateFunctions (/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:224:26)
    at HtmlReport.Report.mix.writeDetailPage (/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:427:9)
    at /Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.extend.writeFile (/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/benjamincoe/bcoe/nyc/node_modules/istanbul/lib/report/html.js:482:23)
```

I rolled back several commits, and it doesn't seem as though this was ever working on `master`.

**Comment by jamestalmage** [comment]
Worked on my machine with `5.1.1` https://github.com/yargs/yarsay/pull/6

**Comment by bcoe** [comment]
@jamestalmage mind trying it with a linked copy of `nyc` on `master`. I thought we'd fixed this, but I can't seem to get it not to explode.

**Comment by jamestalmage** [comment]
yep - it explodes with a linked copy.

**Comment by bcoe** [comment]
@jamestalmage for the life of me I can not seem to isolate the change that is causing this exception in `yarsay` -- it almost seems like a race condition:

1. I rolled nyc back to `5.1.1` and linked in, was able to successfully output an `lcov` report a few times.
2. I moved forward to the next commit, ran tests, and the report again started throwing an exception.
3. I pulled in your most recent fix, and continue to have problems.

I have not seen things fail unless the `--cache` flag is set, really confused.

**Comment by jamestalmage** [comment]
> I moved forward to the next commit, ran tests, and the report again started throwing an exception.

https://github.com/bcoe/nyc/commit/718a31904a63a474c308f21438eb686d55a02a30 definitely broke things.

> I pulled in your most recent fix, and continue to have problems.

#127? That should have fixe what https://github.com/bcoe/nyc/commit/718a31904a63a474c308f21438eb686d55a02a30 broke

**Comment by jamestalmage** [comment]
make sure to clear `node_modules/.cache` and the self coverage files.

**Comment by bcoe** [comment]
Oh, didn't know to remove self coverage will give that a shot.

**Comment by jamestalmage** [comment]
Regenerating self-coverage should also work. We automatically use self-coverage if it exists. If you pull in a change, and try to use it immediately before generating new self-coverage via `node ./build-self-coverage.js` (which is part of `npm test`), then you are actually using covered code from before the merge.

I usually just do `npm run clean` in `nyc` to delete the self coverage. Self coverage *shouldn't* create problems as long as it is up to date, but I'm just paranoid.

 It's also annoying when hunting a bug while linked (your changes to the uncovered code will not be used if `*.covered.js` exists), so my process is usually to just delete it.

**Comment by bcoe** [comment]
fixed by: https://github.com/bcoe/nyc/pull/127
