### ISSUE TITLE
add tests for ./bin/nyc.js

### ISSUE THREAD

**Issue by bcoe** [bcoe/nyc#128]
It would be nice to have some unit tests for the nyc bin, I'm fine with these simply using spawn and asserting against `stdout`/`stderr`.

**Comment by jamestalmage** [comment]
I have found testing to stdout/stderr to be really problematic on Windows. Especially on Node 0.10 (though not exclusively). It's certainly worthwhile to include a handful of integration tests just to make sure all the glue works. Perhaps a better idea would be to run against a fixture with known coverage, and inspect the reports.

**Comment by bcoe** [comment]
@addaleax thanks \o/ see:

https://github.com/bcoe/nyc/pull/224
