### ISSUE TITLE
`package.json`: un-nest `config.nyc` to just `nyc`

### ISSUE THREAD

**Issue by jamestalmage** [bcoe/nyc#131]
According to @sindresorhus, that is [the more common convention](https://github.com/sindresorhus/ava/issues/405#issuecomment-168569929).

Obviously we would need to support the current usage as well for the foreseeable future.

**Comment by bcoe** [comment]
@jamestalmage eyeballed a few other projects such as `standard`, story checks out :+1: let's check both `nyc` and `config.nyc`, but update the documentation to simply `nyc` :+1:
