### ISSUE TITLE
Support for async functions

### ISSUE THREAD

**Issue by KnisterPeter** [bcoe/nyc#133]
Right now nyc fail while handling reverse source-mapping when the original source contains async functions like this one:

```
export function func() {
    return new Promise((resolve, reject) => {
        console.log('test');
        resolve(true);
    });
}
```

```
/tmp/test-cover/node_modules/nyc/node_modules/source-map/lib/array-set.js:91
    throw new Error('No element indexed by ' + aIdx);
    ^

Error: No element indexed by 1
    at ArraySet_at [as at] (/tmp/test-cover/node_modules/nyc/node_modules/source-map/lib/array-set.js:91:11)
    at SourceMapConsumer_originalPositionFor [as originalPositionFor] (/tmp/test-cover/node_modules/nyc/node_modules/source-map/lib/source-map-consumer.js:618:36)
    at mapLocation (/tmp/test-cover/node_modules/nyc/lib/source-map-cache.js:33:25)
    at /tmp/test-cover/node_modules/nyc/lib/source-map-cache.js:93:18
    at Array.forEach (native)
    at SourceMapCache._rewriteStatements (/tmp/test-cover/node_modules/nyc/lib/source-map-cache.js:92:40)
    at /tmp/test-cover/node_modules/nyc/lib/source-map-cache.js:23:11
    at Array.forEach (native)
    at SourceMapCache.applySourceMaps (/tmp/test-cover/node_modules/nyc/lib/source-map-cache.js:15:23)
    at NYC.writeCoverageFile (/tmp/test-cover/node_modules/nyc/index.js:263:25)
    at EventEmitter.onExit.alwaysLast (/tmp/test-cover/node_modules/nyc/index.js:240:11)
```

**Comment by KnisterPeter** [comment]
This is probably related to the 'source-map' module.

**Comment by novemberborn** [comment]
@KnisterPeter could you publish your test code somewhere? It'll make it easier to debug.

**Comment by KnisterPeter** [comment]
@novemberborn Would this be sufficient?
https://gist.github.com/KnisterPeter/cbabf9defb4377f08898

**Comment by novemberborn** [comment]
I see you're using Babel 5. Looks like <https://github.com/sindresorhus/ava/issues/289#issuecomment-161662369>, in which case upgrading to Babel 6 should help.

**Comment by KnisterPeter** [comment]
No, Its TypeScript I'm using. Babel is there to transpile async functions to promises.

**Comment by novemberborn** [comment]
Babel takes the source map from TypeScript and transforms it with the result of it's `async` compilation. The resulting source map is broken, that's what causes the failure. This should be fixed with Babel 6.

**Comment by bcoe** [comment]
@KnisterPeter would you be able to try out `babel@6+`, I'm curious if this solves your issues.

**Comment by bcoe** [comment]
@KnisterPeter bump, I'll be hacking a little bit later tonight and tomorrow let me know if you get a chance to dig into this.

**Comment by KnisterPeter** [comment]
@bcoe I'll have to migrate a whole project, so its not on the easy side. But I will give it a try as soon as possible and report back here. But it could need a week or more...

**Comment by KnisterPeter** [comment]
For babel6 and typescript 1.8 it does work, so I'll close this ticket.

**Comment by novemberborn** [comment]
Thanks for the update @KnisterPeter. Hope you're liking nyc :smile:

**Comment by KnisterPeter** [comment]
Yes its awesome, but currently the source-maps are not 'reverse applied' so we have a big webpacked transpiled coverage report.
This is kind of suboptimal. :grin:

**Comment by novemberborn** [comment]
Could you open an issue for that? Ideally with a test case… I think it might be because we're not correcting the reports for combined source files. That would be an interesting feature to add.

**Comment by KnisterPeter** [comment]
I'll do so later this week.
