### ISSUE TITLE
coloring

### ISSUE THREAD

**Issue by tcurdt** [bcoe/nyc#135]
On a bright terminal the current color scheme is not really working well.

![screen shot 2016-01-09 at 11 57 13](https://cloud.githubusercontent.com/assets/13697/12215713/41bce16e-b6c8-11e5-86dc-e0c439b4f31f.png)

In fact on very few terminal color schemes it's working well.

As a work around `./node_modules/.bin/nyc npm test | cat` works to disable the coloring.

Really not ideal.

**Comment by jamestalmage** [comment]
Green / Yellow / Red is a widely used coloring scheme, used by just about every test runner out there. 

That said, this isn't even an NYC issue, but an istanbul one. We don't create the report. `nyc report` basically delegates to `istanbul report`.

**Comment by bcoe** [comment]
@tcurdt might be worth opening a discussion on:

https://github.com/gotwarlost/istanbul

`red/green` is a bad color scheme for a good chunk of the male population -- so not a crazy idea to bikeshed colors a bit :)

**Comment by jamestalmage** [comment]
> red/green is a bad color scheme for a good chunk of the male population

Ooh - that is a really good point. We may need to rethink the color scheme for AVA as well.

**Comment by tcurdt** [comment]
I am more concerned about the different contrasts for bright/dark themes - but that is indeed a good point. An option to turn off the coloring (be it via instanbul or in nyc) would be nice. For now piping through `cat` works as a work around.
