### ISSUE TITLE
nyc target not found

### ISSUE THREAD

**Issue by harshag** [bcoe/nyc#142]
Getting below error since few hours

`
notarget No compatible version found: nyc@'isaacs/nyc'
00:01:19.701 npm ERR! notarget Valid install targets:
00:01:19.701 npm ERR! notarget ["1.1.0","1.1.1","1.1.2","1.1.3","1.1.4","1.1.5","1.1.6","1.1.7","1.1.8","1.1.9","1.2.0","1.3.0","1.4.0","1.4.1","2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.0.6","2.1.0","2.1.1","2.1.2","2.1.3","2.1.4","2.2.0","2.2.1","2.3.0","2.4.0","3.0.0","3.0.1","3.1.0","3.2.0","3.2.1","3.2.2","4.0.0-alpha","4.0.0","4.0.1","5.0.0","5.0.1","5.1.0","5.1.1","5.2.0","5.3.0"]
00:01:19.701 npm ERR! notarget 
00:01:19.702 npm ERR! notarget This is most likely not a problem with npm itself.
00:01:19.702 npm ERR! notarget In most cases you or one of your dependencies are requesting
00:01:19.702 npm ERR! notarget a package version that doesn't exist.
`

Any idea how to fix this? This is happening only today and there was no change in our codebase to impact this.

**Comment by bcoe** [comment]
@harshag could you share with me your `package.json`, or the `cli` argument that you're running to install `nyc`?

**Comment by harshag** [comment]
@bcoe Below is my package.json. I am not using nyc directly, but guess some other package which I am using is dependent on nyc.
```javascript
{
  "engines": {
    "node": ">= 0.10.0"
  },
  "devDependencies": {
    "grunt": "~0.4.2",
    "grunt-aws": "^0.5.4",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-jshint": "~0.7.2",
    "grunt-contrib-nodeunit": "~0.2.2",
    "grunt-contrib-rename": "0.0.3",
    "grunt-contrib-watch": "~0.5.3",
    "grunt-curl": "~1.4.0",
    "grunt-svn-commander": "^0.1.8",
    "grunt-svninfo": "^0.1.5",
    "grunt-zip": "~0.12.0",
    "load-grunt-tasks": "~0.3.0"
  }
}
```

**Comment by bcoe** [comment]
@harshag this is very strange behavior, it looks like something is trying to install a tag of yargs that never existed.

Try the following:

`npm cache clear; npm i nyc -g`

@isaacs any thoughts about this one?

**Comment by harshag** [comment]
Thanks @bcoe 
I upgraded my npm version to 2 and now it works
