### ISSUE TITLE
Something between 5.0.1 & 5.1.0 made nyc super slow

### ISSUE THREAD

**Issue by timoxley** [bcoe/nyc#146]
I'm experiencing tests that normally take <100ms taking 15-20s when moving nyc from 5.0.1 to 5.1.0. 

It only appears to occur on specific tests, but I'm not exactly sure what's special about these tests without ripping everything apart. We're using babel. Slowness *appears* to occur when trying to hit an HTTP server, not sure if that's actually related though. Tried with cache on and off, no difference.

Nothing particularly jumps out at me from the diff https://github.com/bcoe/nyc/compare/v5.0.1...v5.1.0

Any ideas what could be causing this?

**Comment by jamestalmage** [comment]
Hmm. That's odd. Our require hook did change quite a bit. But it's been universally faster for me since that release.

Is the project open source? Being able to pull down and profile the tests locally would be pretty key in troubleshooting this.

**Comment by bcoe** [comment]
a few things worth checking:

* between `4.x` and `5.x` we changed how `exclude` configuration works, it now takes glob patterns. I would double check that files aren't being instrumented that shouldn't be.
* there was a bug in `spawn-wrap` that was causing files to not be instrumented, I would try downloading to an older version of `spawn-wrap`, and check whether tests speed up.
* @jamestalmage added the `--cache` flag, which can speed up large test-suites significantly; I recommend enabling this flag.

**Comment by isaacs** [comment]
> there was a bug in spawn-wrap that was causing files to not be instrumented, I would try downloading to an older version of spawn-wrap, and check whether tests speed up.

Note: if you were affected by this, then it's possible that tests slowed down because they weren't getting covered before, and now are.  Coverage doubles the number of child processes in play, and adds bookkeeping to every line if code.  It's slower.

**Comment by isaacs** [comment]
(I say that because it shocked me as well, in a few projects, that tests got dramatically slower.  Turns out, it's because coverage started working.)

**Comment by bcoe** [comment]
as @isaacs indicates, the problem is most likely that files that weren't instrumented suddenly started being instrumented 👍
