### ISSUE TITLE
nyc on npm is 2 releases behind

### ISSUE THREAD

**Issue by mateatslc** [bcoe/nyc#153]
version as per CHANGELOG.md: v5.5.0
version out on npm: v5.3.0

Please take a minute to `npm version / publish`, would love to enjoy recent fixes.

**Comment by novemberborn** [comment]
`@next` is used to beta-test the new version in the wild before promoting it to `latest`:

```bash
$ npm dist-tag ls nyc
alpha: 4.0.0-alpha
latest: 5.3.0
next: 5.5.0
```

You can install `nyc@next` or even `nyc@^5.5`, it's just that `npm install nyc` will give you `5.3.0` (for now).

**Comment by mateatslc** [comment]
if `5.5.0` is `next` why `latest` is not `5.4.0` then?
anyways, it makes sense so closing this.

**Comment by novemberborn** [comment]
> if 5.5.0 is next why latest is not 5.4.0 then?

`5.4.0` was `@next`, but then an issue was discovered, hence `5.5.0`.

**Comment by mateatslc** [comment]
cool, thanks!

**Comment by bcoe** [comment]
@mateatslc @novemberborn `nyc@5.5.0` is now latest.
