### ISSUE TITLE
Covers `npm link`ed modules.

### ISSUE THREAD

**Issue by jamestalmage** [bcoe/nyc#154]
If I use `npm link` and then run a test suite using NYC, the linked module ends up generating coverage info. I'm guessing because there is no `node_modules` folder in the parent path for linked modules (at least when using `nvm`).

**Comment by novemberborn** [comment]
Could maybe exclude paths that go above the current directory?

**Comment by sindresorhus** [comment]
I've noticed this too. I npm link a lot and it really makes for a noisy coverage output.

**Comment by novemberborn** [comment]
#160 should resolve this.

**Comment by bcoe** [comment]
@jamestalmage @sindresorhus give this a shot:

`npm i nyc@next`

If it does the trick I'll publish `5.6.0` to latest sometime tomorrow.
