### ISSUE TITLE
Empty coverage output

### ISSUE THREAD

**Issue by micnic** [bcoe/nyc#157]
I created a fake module https://gist.github.com/micnic/f815c0bee18e99805318 and added a test for it, I am using `tap` which uses `nyc` for code coverage. As you can see, If I do not add any additional argument I get an empty output, in case I add `--all` argument the output adds the `index.js` file but it has 0% coverage which is false as the exported function was executed inside the test file.

Does `nyc` avoid somehow my `index.js` file or it is required in the way `nyc` does not expect the file to be required or I am missing something?

**Comment by jamestalmage** [comment]
Try this:

```
tap --coverage index.test.js
```

This issue should really be raised with tap, since you aren't using nyc directly.

**Comment by micnic** [comment]
@jamestalmage actually the `tap` commands that I used are equivalent to:

    nyc check-coverage tap test/index.test.js
    nyc report

that's why I posted here, it gives the same output as before.

I think the problem is somehow related to the `nyc`'s way of tracing required modules or maybe it's something related to `istanbul` module.

**Comment by bcoe** [comment]
Rather than require('fake') I would try require('./) to require the index file.

**Comment by bcoe** [comment]
@micnic did you get a chance to give this a shot?

**Comment by micnic** [comment]
@bcoe yes, I did the change, did not help, the same output, I also tried to run my test using `nyc node test/index.test.js` but without any good news. Then I moved my `fake` folder away from the `node_modules` folder and it worked! It seems that somehow the modules that are inside the `node_modules` are not checked at all by nyc, can you, please, confirm this?

**Comment by novemberborn** [comment]
> It seems that somehow the modules that are inside the node_modules are not checked at all by nyc, can you, please, confirm this?

This is correct, see <https://github.com/bcoe/nyc/#excluding-files>, but I think there's a bug. This is supposed to exclude any dependencies from the coverage report. However if you are testing a dependency its working directory would naturally be inside a `node_modules` directory. We should only be excluding nested and sibling dependencies.

I think behavior should be like this:

path|cwd is `dir/`|cwd is `dir/node_modules/foo/`
---|---|---
`dir/node_modules/foo`|excluded|covered
`dir/node_modules/bar`|excluded|excluded
`dir/node_modules/foo/node_modules/baz`|excluded|excluded

**Comment by novemberborn** [comment]
@micnic could you try with #160?

**Comment by micnic** [comment]
@novemberborn it worked for the fake module, will try a more complex module and will write you when it is ready

**Comment by micnic** [comment]
good news, the tests for the real module have the expected output (with about 28 files).
#160 LGTM!

**Comment by bcoe** [comment]
@micnic could you please try this:

`npm i nyc@next`

I'll publish this version to `latest` tomorrow, if things work well :+1:

**Comment by micnic** [comment]
@bcoe `nyc@next` works fine for me, tried it on two of my modules, waiting for tomorrow release :)
