### ISSUE TITLE
Allow optional file extensions

### ISSUE THREAD

**Issue by Gudahtt** [bcoe/nyc#161]
Would you consider adding support for alternate file extensions?

I'd like to use nyc for a project that uses the `.jsx` file extension, but I can't manage to get it to cover the `.jsx` files. Perhaps I've done something wrong, but it seems as though nyc assumes the files being tested have a `.js` extension.

**Comment by bcoe** [comment]
@Gudahtt I thought we might actually get a request for this :) I like this idea.

@jamestalmage do your require-hook helper modules support alternative extensions? how hard would it be for us to pull this off?

**Comment by lloydcotten** [comment]
@bcoe I took some time to experiment with this.  I think I've determined how this can be done.  Here's the diff: https://github.com/bcoe/nyc/compare/master...lloydcotten:master

If you want I can refactor into a PR.  Was just wondering if the extensions supported should be configurable?  Such as adding them to the nyc config section in package.json, command line args, etc... thoughts?

**Comment by jamestalmage** [comment]
- `append-transform` - [yes](https://www.npmjs.com/package/append-transform#extension)
- `caching-transform` - [yes](https://www.npmjs.com/package/caching-transform#ext), though that option really doesn't affect how the hook is installed (it just changes the suffix so cache entries will be saved with a `.jsx` extension - this helps your IDE open them with the correct pretty highlighting - and makes debugging the cache a little easier to sort through).

@lloydcotten - your branch is mostly on the right track, but I think it should probably be configurable which extensions get added. Also, the correct extension would need to be passed through to `caching-transform` as well.

This issue might also be relevant to implementers: https://github.com/jamestalmage/append-transform/issues/6

**Comment by lloydcotten** [comment]
I've updated my branch trying to take into account some of the suggestions / info from @jamestalmage.  Just wanted to post the diff here again for review to see if I'm getting close to good.  If so, I can submit this as a PR.  https://github.com/bcoe/nyc/compare/master...lloydcotten:master

There aren't any additional tests yet, mainly because I'm not used to the way these tests are done and,  to be honest, was having a little trouble following exactly what was going on.  If you can provide some guidance as to how this change could be tested using a similar pattern to what's already there, I can certainly take a crack at it.

**Comment by jamestalmage** [comment]
@lloydcotten - It's best just to open a PR. You can prefix it with `[WIP]` (meaning "Work in Progress") if you feel it's not ready to be merged yet.

An actual PR makes it a lot easier for all of us to review and give feedback.

**Comment by lloydcotten** [comment]
Thanks for the feedback @jamestalmage.  I added PR #163.

**Comment by bcoe** [comment]
@lloydcotten @Gudahtt give this a shot:

`npm i nyc@next --save-dev`

I'll promote to `nyc@latest` once people have played with it for a bit.

**Comment by Gudahtt** [comment]
I've just tested this - seems to work great! Thanks!
