### ISSUE TITLE
opts/command line args precedence over config is inconsistent

### ISSUE THREAD

**Issue by lloydcotten** [bcoe/nyc#165]
While doing pull request #163, I noticed that nyc will take config from package.json over command line args and/or opts passed into the NYC constructor for some cases, but will take opts over config for other values (namely `cwd`).  See these lines:
https://github.com/bcoe/nyc/blob/master/index.js#L34
https://github.com/bcoe/nyc/blob/master/index.js#L64

I patterned the new `extension` config after the `require` config where config from package.json is preferred:
https://github.com/bcoe/nyc/blob/master/index.js#L54

To me (and @novemberborn seems to agree) this is not intuitive.  The only way command line args or opts are used for these properties, is if no package.json config exists.  If we switched it around, it would make testing a bit easier, and would be more intuitive for usage when mixing package.json config and command line usage.

**Comment by bcoe** [comment]
@lloydcotten my plan is to moving to having yargs load the configuration:

https://github.com/bcoe/nyc/issues/156

Command-line arguments will take precedence over package.json configuration when I make this change :+1:  Mind adding a note to #156

**Comment by lloydcotten** [comment]
Sounds good.
