### ISSUE TITLE
Code mapping after an error occurs

### ISSUE THREAD

**Issue by aureooms** [bcoe/nyc#168]
I'm running nyc with ava. When a runtime error occurs in a test (e.g. trying to access a key of `undefined`), ava outputs the stacktrace with lineno:col inside the instrumented file, not the original file. Would it be possible to map the instrumented code back to the original code and output the relevant lineno:col?

**Comment by novemberborn** [comment]
@aureooms nyc uses [Istanbul](https://github.com/gotwarlost/istanbul) to instrument the files. You'd probably need Istanbul to include a source map when it instruments a file, and it would have to take into account input source maps in case of ES2015 transpilation. Then it may or may not work automatically with AVA.

I don't think Istanbul supports this currently so you'd have to open an issue there.

**Comment by bcoe** [comment]
@aureooms give this a spin:

https://github.com/bcoe/nyc#use-babel-plugin__coverage__-for-better-es6es7-support

we've released better support for ES6/ES6 coverage using the `__coverage__` instrumentation library.
