### ISSUE TITLE
--all doesn't use configured file extensions

### ISSUE THREAD

**Issue by novemberborn** [bcoe/nyc#174]
#163 introduced configurable file extensions however `--all` only selects `**/*.js` files. We could generate that pattern for all configured extensions and then use [`globby`](https://www.npmjs.com/package/globby) to load the files.

**Comment by novemberborn** [comment]
@lloydcotten perhaps you'd be interested in improving this? No obligation of course :smiley_cat:

**Comment by lloydcotten** [comment]
Hmm... I see.  Yes, perhaps I could look at that.
