### ISSUE TITLE
Should define something easy searchable alias for nyc

### ISSUE THREAD

**Issue by LimeStreem** [bcoe/nyc#179]
I'm recently struggling to use this library. 
When I search about nyc in Google, of course it reach something related to New york city. That is not problem.

However, even I searched in "nyc code coverage" or "nyc node", most of pages are the pages related to Hackathon or conferences. 

Download count of this library is currently growing, so I guess many people will struggle with this problem when many people use this library. Therefore, I suggest to define something alias for nyc. 
For example, if you name code name for nyc versions like Android versions, users will write articles with these name, and articles related to nyc will be easier to be found in Google.

**Comment by novemberborn** [comment]
I found the easiest way to learn more about a particular package is to use `http://npm.im/{PACKAGE_NAME}`, which redirects to the npm page for that package. That page usually has a README and links to issue trackers etc.

**Comment by bcoe** [comment]
@LimeStreem I've struggled with this as well, I like the name `nyc` but it does make the library hard to search for. any thoughts?

Perhaps change the README.md to:

> nyc - for coverage

**Comment by bcoe** [comment]
the name nyc, and this project, seems to be getting some traction ... I think we can stick with the short hard to search name at this point.
