### ISSUE TITLE
question: my coverage went up after updating to nyc@6. what changed?

### ISSUE THREAD

**Issue by jonathanong** [bcoe/nyc#186]
can't tell from the changelog: https://github.com/bcoe/nyc/blob/master/CHANGELOG.md#change-log

just wondering.

close this issue at will! and thanks!

**Comment by novemberborn** [comment]
There were source map related improvements in 5.5.0 and 5.6.0, maybe that's it. Do you recall what version you upgraded from?

Regardless, higher coverage numbers are good right? :grinning:

**Comment by jonathanong** [comment]
from 5.6 to 6! yes it's good, but i can't tell what coverage actually changed so i'm a litttttle worried

**Comment by bcoe** [comment]
@jonathanong if you look at the `lcov` visual report running on `5.6.0` and `6.0.0`, does anything jump out at you?

**Comment by bcoe** [comment]
@jonathanong I'm going to close this unless any issues have jumped out at you, I think @novemberborn is probably correct that it's changes to source maps that increased your coverage -- it's probably more correct :+1:

**Comment by jonathanong** [comment]
i found it. it's because the API for setting the excluded paths changed in `package.json`. it started counting coverage of all my tests, which are 99.9% or something.

fixed the config and my coverage is now correct again.
