### ISSUE TITLE
nyc@6 breaks my tests

### ISSUE THREAD

**Issue by GitScrum** [bcoe/nyc#187]
Hi, i heve [broken tests in travis](https://travis-ci.org/GitScrum/posthtml-cli/jobs/114118483), if used nyc@5.2.0 all my test is passed.

**Comment by bcoe** [comment]
@GitScrum there appears to be a strange issue happening caused by `yargs@6.2.0`, simply adding:

`delete require.cache[require.resolve('yargs')]`

to the top of `cli.js` solves the problem. it seems like the fix for this bug should ultimately be in yargs.

**Comment by GitScrum** [comment]
Thank you very much. 👏👏👏
