### ISSUE TITLE
support question - good grief

### ISSUE THREAD

**Issue by ORESoftware** [bcoe/nyc#188]
the examples show:

```bash
nyc npm test
```
but what about a simple example with

```bash
nyc test/test1.js
```

Is this possible?

**Comment by jamestalmage** [comment]
> Is this possible?

Yes, though you might need to do:

```
nyc node test/test1.js
```

**Comment by ORESoftware** [comment]
alright thanks will give that a go

**Comment by ORESoftware** [comment]
is this not a common request, why is it not in the readme I wonder

**Comment by jamestalmage** [comment]
> is this not a common request

You are the first! No it's not really that typical. Most people use a runner launched with a common API, so they are doing something like one of the following:

```
$ nyc mocha test/test1.js
$ nyc tap test/test1.js
$ nyc ava test/test1.js
```

Is your issue resolved?

**Comment by ORESoftware** [comment]
if you don't mind pls keep open til tomorrow, have to test on windows thx

**Comment by bcoe** [comment]
@ORESoftware is it okay to close this issue? Do you think there's any documentation that we could add to README.md?

**Comment by ORESoftware** [comment]
Thanks, go ahead and close, I haven't tested on windows yet, bu will later today, most likely it will be fine
