### ISSUE TITLE
Regression: the require option cannot be set in package.json

### ISSUE THREAD

**Issue by jwhitfieldseed** [bcoe/nyc#189]
[This demo project](https://github.com/jwhitfieldseed/nyc-issue-189) repoduces the issue.

The `--require` flag causes nyc to load libraries, but `nyc.require` in `package.json` does not.

package.json:
```json
{
  "dependencies": {
    "babel-register": "^6.6.5",
    "babel-preset-es2015": "^6.6.0",
    "nyc": "^6.0.0"
  },
  "scripts": {
    "test": "nyc node -- test.js",
    "test-with-flag": "nyc --require babel-register node -- test.js"
  },
  "nyc": {
    "require": ["babel-register"]
  }
}
```

I also tried `"require": "babel-register"`, with the same result.

test.js:
```javascript
import { readFile } from "fs";
console.log("ok");
```

Outcome:

```
❯ npm run test-with-flag

> nyc-require-issue@1.0.0 test-with-flag /Users/joe/code/nyc-require-issue
> nyc --require babel-register node -- test.js

ok
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|
```

```
❯ npm run test

> nyc-require-issue@1.0.0 test /Users/joe/code/nyc-require-issue
> nyc node -- test.js


/Users/joe/code/nyc-require-issue/test.js:1
(function (exports, require, module, __filename, __dirname) { import { readFil
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
... etc ...
```

In NYC 5 I successfully used this config snippet:

```json
"config": {
  "nyc": {
    "require": ["babel-register"]
  }
}
```

**Comment by bcoe** [comment]
see: https://github.com/bcoe/nyc/issues/189

**Comment by bcoe** [comment]
@jwhitfieldseed give this a shot:

`npm i nyc@next`

Should fix the issues you were seeing. If everyone's tests are looking good I'll promote to `latest` soon.

**Comment by rpominov** [comment]
Not sure if this is the same issue, but `all` also doesn't seem to work when set via package.json. And it isn't fixed in `nyc@next`.

**Comment by bcoe** [comment]
@rpominov there's a fix here:

https://github.com/bcoe/nyc/pull/194/files

I'll publish this to `nyc@next` so you can test as soon as tests pass.

**Comment by bcoe** [comment]
@rpominov released the patch:

`npm cache clear; npm i nyc@next`

**Comment by rpominov** [comment]
@bcoe Works great now. Thanks!

**Comment by jwhitfieldseed** [comment]
The fix is great, thanks @bcoe :+1:
