### ISSUE TITLE
exclude behavior change between 5.x and 6.x

### ISSUE THREAD

**Issue by MoOx** [bcoe/nyc#196]
```js
  "config": {
    "nyc": {
      "exclude": [
        "**/__tests__/**/*.js"
      ],
      "include": [
        "src/**"
      ]
    }
  },
```

This config was consuming code in src, but not files like `src/PageContainer/__tests__/component.js` in 5.x.
With 6.1.1, those files in `__tests__` are counted in the % which sucks.

**Comment by MoOx** [comment]
I had to add two pattern

```
        "**/__tests__/**/*.js",
        "**/__tests__/*.js"
```

Which looks like a regression to me :)

**Comment by MoOx** [comment]
FYI, `"**/__tests__/**"` also works (yeah).

**Comment by bcoe** [comment]
@novemberborn any thoughts about this, perhaps an update in how we process globs?

**Comment by MoOx** [comment]
It seems I was wrong on the entire thing and confused by the order of reported file.
It seems  config is not in "config.nyc" but just "nyc", is this correct?

**Comment by bcoe** [comment]
@MoOx yes, this was the breaking change between 5.x and 6.x -- we switched to using a new built in yargs feature to handle loading config from package.json.

Cool to close this?

**Comment by MoOx** [comment]
Yeah can close.

One detail for better ux: provide a warning if people miss the config definition change :)
