### ISSUE TITLE
Bad application of source maps to coverage reports for ternary expressions

### ISSUE THREAD

**Issue by skozin** [bcoe/nyc#198]
I don't know for sure where I should report this issue, so sorry if it doesn't belong here.

When I generate coverage report with `nyc ava && nyc report --reporter=html`, the resulting report shows incorrect highlighting of the source code. And, the most critically, overall coverage numbers for branches and functions look incorrect (much less than expected).

I have prepared [the repo](https://github.com/skozin/nyc-babel-issue-repro) with the reproduction case.<br>Also, I've uploaded the report to [this GH pages site](http://skozin.github.io/nyc-babel-issue-repro/nyc-babel-issue-repro/index.html).

Here is a screenshot that shows incorrect highlighting:

![image](https://cloud.githubusercontent.com/assets/1699593/13906228/6f55a302-eee2-11e5-8069-df3ef42d27c5.png)

Annotations on the left suggest that `_takeFromWaitingPublisher()` function has been executed multiple times, and that's indeed the case as the test code is crafted to ensure this. Yet it is highlighted as not being covered.

The `_take()` function also has a similar problem, although its code is highlighted in yellow, which means "branch not covered". However, the highlighted code has clearly been executed multiple times.

Also, the highlighting sometimes starts and ends at positions that make no sense, e.g. between "t" and "h" letters inside `this` keyword.

**Comment by bcoe** [comment]
@skozin does the percentage of coverage seem correct, but the highlighting off? This is most likely a problem with how we remap from the sourcemap to the coverage files used by Istanbul; @novemberborn is a subject matter expert on this part of the codebase.

**Comment by skozin** [comment]
@bcoe no, 

> And, the most critically, overall coverage numbers for branches and functions look incorrect (much less than expected).

**Comment by skozin** [comment]
It reports 75% Branches (33/44) and 66.67% Functions (4/6), although all functions except one have been executed, and almost all branches inside them was taken.

**Comment by skozin** [comment]
I've simplified the case a little. Now nyc reports 73.68% Branches (28/38) and 66.67% Functions (4/6). The function coverage I expect to see is 80%:

```
Covered:

constructor: 1x
take: 24x
anon inside take: 24x
_take: 24x
_takeFromWaitingPublisher: 9x
_triggerWaiters: 9x
_emitDrain: 1x
assert: 49x

Not covered:

anon at the end of _take
nop

Total:

80% (8/10)
```

**Comment by skozin** [comment]
Also, If I move from ES6 classes to plain functions, the functions coverage numbers (both percentage and count) start to match the expected ones.

**Comment by novemberborn** [comment]
@skozin I'll try and have a look at this tomorrow.

**Comment by skozin** [comment]
@novemberborn Thanks a lot!

**Comment by novemberborn** [comment]
@skozin finally got round to this. First I compiled `index.js` directly (`$(npm bin)/babel index.js --out-dir build`) and switched the tests to use `./build/index.js`. The coverage report looked good:

![screen shot 2016-03-24 at 13 14 01](https://cloud.githubusercontent.com/assets/33538/14017879/54ef0296-f1c2-11e5-92cc-7457e64e252e.png)

I then looked more closely at the locations in your original code where the coverage report goes wrong. These are ternary expressions. When I [reformat them](https://github.com/novemberborn/nyc-babel-issue-repro/commit/111f7424c704fd50fb8b2bbd003d7c347048f14f) the report matches that of the Babel build output:

![screen shot 2016-03-24 at 13 15 50](https://cloud.githubusercontent.com/assets/33538/14017923/a5131c9e-f1c2-11e5-8582-6054319484bf.png)

The conclusion then is that we're having trouble converting coverage reports for certain ternary expressions. I haven't investigated whether this is an issue with the coverage reports from Istanbul or our conversion logic.

I suppose you could reformat your code a little until this gets fixed properly. Thanks for finding this!

**Comment by novemberborn** [comment]
For future reference, using braces [in the arrow function](https://github.com/novemberborn/nyc-babel-issue-repro/commit/111f7424c704fd50fb8b2bbd003d7c347048f14f#diff-168726dbe96b3ce427e7fedce31bb0bcR69) also breaks the source map application.

The repo with the original test case and a workaround is at <https://github.com/novemberborn/nyc-babel-issue-repro>.

**Comment by skozin** [comment]
@novemberborn, great, thanks for your help! I'll reformat my trenaries as a temporary solution.

And what do you think about incorrect Funcs numbers I described in previous comments?

> I've simplified the case a little. Now nyc reports 73.68% Branches (28/38) and 66.67% Functions (4/6). The function coverage I expect to see is 80% (8/10):
>
> ```
> Covered:
> 
> constructor: 1x
> take: 24x
> anon inside take: 24x
> _take: 24x
> _takeFromWaitingPublisher: 9x
> _triggerWaiters: 9x
> _emitDrain: 1x
> assert: 49x
> 
> Not covered:
> 
> anon at the end of _take
> nop
> 
> Total:
> 
> 80% (8/10)
> ```
>
> Also, If I move from ES6 classes to plain functions, the functions coverage numbers start to match the expected ones: 80% (8/10). See the [no-class branch](https://github.com/skozin/nyc-babel-issue-repro/tree/no-class).
>
> So the issue with incorrect functions stats has something to do with how Babel transpiles ES2015 classes (any maybe other constructs).
>
> Also note that the reported total number of functions differs when comparing [master](https://github.com/skozin/nyc-babel-issue-repro/blob/master/coverage/nyc-babel-issue-repro/index.js.html#L34) (6 functions incorrectly reported) with [no-class](https://github.com/skozin/nyc-babel-issue-repro/blob/no-class/coverage/nyc-babel-issue-repro/index.js.html#L34) (10 functions correctly reported), though these branches differ only in the presence of `class` construct around the functions.

Should I open another issue for this?

**Comment by novemberborn** [comment]
@skozin if I take your `no-class` branch and apply the ternary workarounds I see the same uncovered lines as in the report for the built file (without source maps). I imagine any other mismatch is because of the ternary issue.

**Comment by skozin** [comment]
@novemberborn, probably there is some misunderstanding here.

See, I run coverage on [`no-class-workaround` branch](https://github.com/skozin/nyc-babel-issue-repro/tree/no-class-workaround), which is the same as `no-class`, but with trenaries and arrow functions workarounds applied, and get the following:

```
------------------------|----------|----------|----------|----------|----------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------|----------|----------|----------|----------|----------------|
 nyc-babel-issue-repro/ |    90.32 |    73.68 |       80 |    90.32 |                |
  index.js              |    90.32 |    73.68 |       80 |    90.32 |... 3,44,93,112 |
------------------------|----------|----------|----------|----------|----------------|
All files               |    90.32 |    73.68 |       80 |    90.32 |                |
------------------------|----------|----------|----------|----------|----------------|
```

HTML report shows `80% Functions 8/10`. These are the correct numbers.

Now I run the coverage on [`workaround` branch](https://github.com/skozin/nyc-babel-issue-repro/tree/workaround), which is the same as `master`, but with workarounds applied, and get the following:

```
------------------------|----------|----------|----------|----------|----------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------------|----------|----------|----------|----------|----------------|
 nyc-babel-issue-repro/ |    89.29 |    73.68 |    66.67 |    89.29 |                |
  index.js              |    89.29 |    73.68 |    66.67 |    89.29 |... 3,44,93,113 |
------------------------|----------|----------|----------|----------|----------------|
All files               |    89.29 |    73.68 |    66.67 |    89.29 |                |
------------------------|----------|----------|----------|----------|----------------|
```

HTML report shows `66.67% Functions 4/6`. The functions total now is `6`, which is obviously not correct, as there are total `10` functions (8 class methods and 2 anonymous fns inside these methods). Also, the coverage, in comparison with `no-class-workaround` branch, has decreased from `80%` (8 funcs of 10) to `66.67%` (4 funcs of 6).

I guess this is not what one would expect. Note that highlighting in HTML report is correct in both branches, and that there are no other differences between the two branches, except that in `workaround` all functions are declared inside the class body.

**Comment by skozin** [comment]
I've updated the branches to match more closely. Actually, now it's enough to see the diff, which now also contains coverage numbers: https://github.com/skozin/nyc-babel-issue-repro/compare/workaround...no-class-workaround.

**Comment by skozin** [comment]
I'm not actually sure these invorrect functions numbers are caused by nyc, maybe this is an issue/feature in istanbul.

**Comment by novemberborn** [comment]
@skozin yea I'm starting to think applying the source maps to Istanbul's coverage report is wrong. We need raw execution info, map that back to the original source, and then determine coverage.

Will keep your cases in mind when I/someone gets round to improving the behavior here.

**Comment by novemberborn** [comment]
@skozin apparently this may be solved in future Istanbul versions, though I don't know how compatible those will be with nyc. See https://github.com/gotwarlost/istanbul/issues/582#issuecomment-201318773

**Comment by skozin** [comment]
@novemberborn, thanks for considering my cases, and for the link. Hope it will be compatible)

**Comment by bcoe** [comment]
@skozin closing in favor of https://github.com/bcoe/nyc/pull/266
