### ISSUE TITLE
Coverage when using mocha --watch

### ISSUE THREAD

**Issue by ItsCosmo** [bcoe/nyc#200]
nyc works as expected unless I add `--watch` flag to mocha, in which case no coverage is generated at all, nor is the `.nyc_output` folder populated with anything. Is this something that would be expected to work?

`NODE_ENV=test ./node_modules/.bin/nyc --require babel-core/register --reporter=lcov mocha "test/**/*spec.js" --require ./test/helper.js --watch`

**Comment by novemberborn** [comment]
> Is this something that would be expected to work?

No. nyc only generates coverage when all child processes exit, which is not the case in `--watch` mode. You'll have to generate coverage separately I'm afraid.

**Comment by JetUni** [comment]
Is it possible that this behavior could be changed? I'd really like to be able to update the coverage as I'm adding to my tests. It's very helpful to be able to see quickly what changes improve coverage. I'd even be willing to help with a PR if given a little guidance. I just spent a little time browsing through the code and I understand parts of it now. Thanks

**Comment by Sayan751** [comment]
I am facing the same issue. I understand that as per [current workflow](https://github.com/istanbuljs/nyc/blob/master/bin/nyc.js#L89-L116) it might be difficult to generate the coverage report after every execution of all the suites.

I have a mocha-based setup. And one thing you can do pretty easily in mocha is to create custom reporter. I recently used this technique to [combine multiple reporters](https://stackoverflow.com/questions/27709429/how-to-generate-multiple-reports-with-mocha/60095471#60095471). You may also refer to this tutorial: https://mochajs.org/api/tutorial-custom-reporter.html

I think a viable solution might be to create different packages for different test frameworks to add event handlers accordingly. For example, I tried the following (although without 100% success), to tap into mocha's events

```javascript
runner.on(mocha.Runner.constants.EVENT_RUN_END, () => {
  const nycReport = spawn('nyc', ['report', '--nycrc-path', './tests/nyc.config.js'], { shell: true });
  nycReport.stdout.on('data', (data) => {
      console.log(data.toString());
  });
  nycReport.on('close', () => {
      kill(nycReport.pid);
  });
});
```

I am not sure whether this is the way to go. Just wanted to throw this idea here, as this is quite a common requirement, and the argument "covering the watch mode is useless" does not hold.
