### ISSUE TITLE
Running with `karma start` only covers karma.conf.js

### ISSUE THREAD

**Issue by joerideg** [bcoe/nyc#203]
Hi,
I am trying to make my current build setup work with nyc. 

Currently I have a karma setup that simply takes 1 .js file and runs 1 test from a .spec.js file. 
Running `karma start` will output 1 succesfull test.

Now when I run it with nyc (globally installed) with `nyc karma start` it finishes succesfully but the coverage is showing coverage on the karma.conf.js?

The project is located [here](https://github.com/onehippo/hippo-ngbp/tree/nyc-coverage)
I feel like im doing something obvious wrong and any help would be appreciated. If you need more info please let me know.

regards,
Joeri

**Comment by jamestalmage** [comment]
`nyc` only works to provide coverage for code run in forked Node.js processes. `karma` runs code in the browser - `nyc` is not the appropriate tool for providing coverage. See the karma docs. I believe they provide a recipe for coverage.

**Comment by jamestalmage** [comment]
https://github.com/karma-runner/karma-coverage

**Comment by joerideg** [comment]
ok thanks james!

**Comment by ethanyanjiali** [comment]
in Karma document it says "Karma can generate code coverage using awesome Istanbul."
https://karma-runner.github.io/0.8/config/coverage.html
