### ISSUE TITLE
Can't enable cache in package.json nyc stanza

### ISSUE THREAD

**Issue by novemberborn** [bcoe/nyc#204]
This doesn't enable the cache:

```json
"nyc": {
  "cache": true
}
```

I need to enable it through `nyc --cache`. @bcoe is this an issue with yargs maybe?

Also when will we enable the cache by default?

**Comment by bcoe** [comment]
@novemberborn what do the commands you're running look like, I'm able to enable the cache in the `nyc` block with `nyc@6.1.1` -- I do see an issue with config options not being passed to the `report` and `check-coverage` commands, which should be fixed (but I doubt is related).

Could you share the repo having issues?

**Comment by novemberborn** [comment]
> Could you share the repo having issues?

Yea sorry, it wasn't live before. See <https://github.com/novemberborn/x690>. `npm run coverage`. If I remove the `--cache` option and instead specify `"cache": true` I don't see `node_modules/.cache/nyc` being created. `argv.cache` in `bin/nyc.js` is `false`.

**Comment by bcoe** [comment]
@novemberborn aha! see the problem, `nyc` is accidentally nested under `eslintConfig` rather than being at the top level.

**Comment by novemberborn** [comment]
Duh :blush:
