### ISSUE TITLE
'Branch not covered'

### ISSUE THREAD

**Issue by willin** [bcoe/nyc#206]
https://github.com/gotwarlost/istanbul/issues/582#issuecomment-201318773

**Comment by willin** [comment]
<img width="518" alt="qq20160328-1 2x" src="https://cloud.githubusercontent.com/assets/1890238/14068963/d4a31270-f4c4-11e5-852e-d35b52a64d59.png">

**Comment by novemberborn** [comment]
Hey @willin we actually realized this the other day, see #198.

Didn't know Istanbul had some alpha branches that might fix this though. Thanks!
