### ISSUE TITLE
`include` option doesn't supported in CLI

### ISSUE THREAD

**Issue by rpominov** [bcoe/nyc#207]
Can it be added to CLI options? I can submit a PR if it'll help.

**Comment by jamestalmage** [comment]
Do you have a use case where you are unable to just use the config in `package.json`?

**Comment by rpominov** [comment]
Yeah, I'm building a tool that basically gives you an opinionated dev environment. It runs test compiles js etc. Also it does coverage, so nyc is just implementation detail of that tool, and nyc config have to be hidden from the tool's user. Currently I just pass all options via CLI, which works fine, except `include` can't be specified via CLI options.

Here is the link if you're interested https://github.com/rpominov/lobot . I just run `lobot coverage` or `lobot coveralls` and it does stuff using `nyc` under the hood.
