### ISSUE TITLE
Return non-zero exit code when coverage is below required minimum

### ISSUE THREAD

**Issue by tp** [bcoe/nyc#209]
Would you be open to discuss the possibility to return a non-zero exit code when the coverage is below the minimum thresholds set?

Or do you feel like this should be handled by external systems, working on the coverage data?

**Comment by addaleax** [comment]
Is [this](https://github.com/bcoe/nyc#checking-coverage) what you are looking for?

**Comment by tp** [comment]
Yes, adding `--check-coverage=true` gets the behavior that I wanted. :-) Thanks!

**Comment by tp** [comment]
The only issue I have found is that this still returns 0 even when ava (the test command I use) returns a non-zero exit code because tests failed.

Wondering how to best check the test result and coverage in one go, or whether I need to analyze the output of the different tools to get a combined result.

**Comment by addaleax** [comment]
I think that’s actually a bug, yep. For now, you should be able to run `nyc ava …` and `nyc check-coverage` separately to check their exit codes.

**Comment by bcoe** [comment]
@tp shoot, yes we should patch this! please open an issue if you have a second, and patches very much welcome.
