### ISSUE TITLE
empty .nyc_output folder

### ISSUE THREAD

**Issue by ericmdantas** [bcoe/nyc#213]
Hello,

I've been trying to run coverage of the simplest repo possible [here](https://github.com/ericmdantas/node-playground), but I can't get `.nyc_output` to be filled - which, I believe, leads me to the error: 

```
[error] "2016-04-03T03:21:55.775Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2016-04-03T03:21:55.777Z"  'input: ' ''
[error] "2016-04-03T03:21:55.778Z"  'error from convertLcovToCoveralls'
```

I've run `$ nyc ava` and suchs and still don't have a `.nyc_output` folder filled. When it's generated, it's empty. The coverage shows in the console, but there's no files in there.

Here's the whole app:

*index.js*
```js
"use strict";

exports.Something = class Something {
  doIt() {
    console.log('yo!');
  }
}
```

*index_test.js*
```js
import test from 'ava';
import {Something} from './';

test('ava test - 0', t => {
  let s = new Something();
  s.doIt();

  t.pass();
});

test('ava test - 1', t => {
  let s = new Something();
  s.doIt();

  t.pass();
});

test('ava test - 2', t => {
  let s = new Something();
  s.doIt();
  
  t.pass();
});

```

*package.json - scripts and deps (travis-after-success is the one that fails with the error above)*
```json
  "scripts": {
    "test": "ava **/*_test.js",
    "cov": "nyc npm t",
    "travis-after-success": "nyc report --reporter=text-lcov | coveralls"
  },
  "devDependencies": {
    "ava": "^0.13.0",
    "coveralls": "^2.11.9",
    "nyc": "^6.1.1"
  }
```

**Comment by sarbbottam** [comment]
could you try using
`"cov": "nyc ava **/*_test.js",`

instead of 
`"cov": "nyc npm t",`

**Comment by ericmdantas** [comment]
That did it, @sarbbottam! Thanks :smile:

**Comment by sibajeeray** [comment]
The problem is, Mocha is not exiting after its execution. So coverage report is unable to print as the execution is hold by mocha.
In Script of package.json mention --exit after mocha.
EX- nyc --reporter=html --reporter=text mocha --exit
