### ISSUE TITLE
Html report broken

### ISSUE THREAD

**Issue by jmdobry** [bcoe/nyc#215]
nyc appears to correctly report code coverage when it prints to the console:

<img width="627" alt="screen shot 2016-04-03 at 10 24 13 am" src="https://cloud.githubusercontent.com/assets/1213510/14233761/6b1beda6-f986-11e5-895c-9cf6c17e2210.png">

But when I then run `nyc report --reporter=html` the generated html report is useless:

<img width="536" alt="screen shot 2016-04-03 at 10 24 58 am" src="https://cloud.githubusercontent.com/assets/1213510/14233763/70794bcc-f986-11e5-965c-aa801b9704da.png">

The code in that image is executed hundreds of times during the tests, but the html report shows nothing.

I feel like I'm missing something, perhaps related to source maps. You can see that the source file under test is `dist/js-data.js`. `dist/js-data.js.map` is available, but the source map seems to be ignored, as nyc doesn't split the report up for the individual files that were bundled into `dist/js-data.js`.

Steps to reproduce:

1. `git clone https://github.com/js-data/js-data.git`
1. `cd js-data`
1. `git checkout v3`
1. `npm install`
1. `npm test`
1. `npm run html-report`
1. `open coverage/index.html`

Thanks for any help. I'd love to get coverage reporting for the individual source files, in addition to an html report that tells me which lines I still need to cover.

**Comment by jmdobry** [comment]
Okay, my problem is that I'm transpiling and bundling my sources from running the tests, instead of letting ava transpile my sources.

**Comment by jamestalmage** [comment]
@jmdobry 

Your best bet is to transpile with source-maps (either embedded our external `.map` linked files).

If you don't want to deploy source-maps, transpile to `protectDir/build` with embedded source-maps, and use those for testing, transpile to `projectDir/lib` for deploying (without source-maps). I usually do it this way anyways, and add `projectDir/build` to `.gitignore` - that way the `dist` folder only gets updated when I do a version bump.

**Comment by jamestalmage** [comment]
Closing. Feel free to open another issue if you think there's something `nyc` can do to make this less painful.

**Comment by jmdobry** [comment]
This is what I ended up with:

```json
"babel": {
  "presets": [
    "es2015",
    "stage-0"
  ]
},
"ava": {
  "babel": "inherit",
  "files": [
    "test/**/*.js"
  ],
  "source": [
    "src/**/*.js"
  ],
  "require": [
    "babel-register"
  ]
},
```

Which now gives me coverage reporting for individual source files. However, at the very first occurence of a "not covered branch" in the html report, the css paints the entire rest of the page yellow.

**Comment by jamestalmage** [comment]
Try adding `sourceMaps: "inline"` to the babel portion of the config.

**Comment by jmdobry** [comment]
Didn't make a difference. If I inspect the html, the first occurrence of a "not covered branch" starts with:

```html
<span class="branch-1 cbranch-no" title="branch not covered">
```

Instead of that `span` closing at the end of the not covered code, it continues and the entire rest of the page's html is nested under that `span`, and is therefore painted yellow because of the `cbranch-no` class.

**Comment by jamestalmage** [comment]
Hmm. That almost seems like an istanbul issue. I'm not sure how our source-map remapping could impact that.

**Comment by jmdobry** [comment]
I guess it's not a big deal, it just forces me to add coverage from the top of the file on down.

**Comment by jamestalmage** [comment]
> I guess it's not a big deal, it just forces me to add coverage from the top of the file on down.

It should be fixed. Either in istanbul or here.

**Comment by jamestalmage** [comment]
@jmdobry - Can you create a minimal reproduction on GItHub that @novemberborn and I can clone and play with.

**Comment by jmdobry** [comment]
There may already be an open issue: gotwarlost/istanbul#557

**Comment by bcoe** [comment]
@jmdobry closing in favor of https://github.com/bcoe/nyc/pull/266

**Comment by bcoe** [comment]
@jmdobry give this a spin:

https://github.com/bcoe/nyc#use-babel-plugin__coverage__-for-better-es6es7-support

we've released better support for ES6/ES7 coverage using the coverage instrumentation library.

**Comment by jmdobry** [comment]
I'll give it a try
