### ISSUE TITLE
nyc causes tests to fail under Node 0.8, 0.10, and 0.12

### ISSUE THREAD

**Issue by othiym23** [bcoe/nyc#231]
The title is a little vague because I haven't had time to isolate the actual failure. You can see it in [this Travis build](https://travis-ci.org/npm/npm/builds/122993477). The failure is the same in all cases:

```
test/tap/unit-gentlyrm.js ........................... 70/82
  isSafeToRm
  not ok TypeError: Object.keys called on non-object
    at:
      native: true
      function: Function.keys
    stack: |
      makeObjUsePlatformPaths (test/tap/unit-gentlyrm.js:26:12)
      test/tap/unit-gentlyrm.js:28:18
      makeObjUsePlatformPaths (test/tap/unit-gentlyrm.js:26:22)
      test/tap/unit-gentlyrm.js:28:18
      makeObjUsePlatformPaths (test/tap/unit-gentlyrm.js:26:22)
      test/tap/unit-gentlyrm.js:41:27
      testNotIsSafeToRm (test/tap/unit-gentlyrm.js:342:5)
      test/tap/unit-gentlyrm.js:381:3
    test: isSafeToRm
    message: 'TypeError: Object.keys called on non-object'
  
  isSafeToRm
  not ok missing test
  isSafeToRm
  not ok missing test
  isSafeToRm
  not ok missing test
  isSafeToRm
  not ok missing test
  isSafeToRm
  not ok missing test
  isSafeToRm
  not ok missing test
  isSafeToRm
  not ok missing test
  isSafeToRm
  not ok missing test
  isSafeToRm
  not ok missing test
  isSafeToRm
  not ok missing test
  isSafeToRm
  not ok missing test
```

That build was run against [this branch](https://github.com/npm/npm/commits/othiym23/restandardificationated) of the npm CLI. I'm very impressed with how well `nyc` handles npm's truly baroque test suite, by the way. I only had to make [one change](https://github.com/npm/npm/commit/785f3559717f989a3698ff64abb7ffab0026330d) to the tests to get them working under nyc in my local dev environment.

**Comment by bcoe** [comment]
@addaleax I told @othiym23 I'd been working with someone who's addicted to debugging hard issues like this, don't suppose this might be a class of problem you could help with?

We'd love to get coverage working for all of npm's tests.

**Comment by iarna** [comment]
The code in question is:
```
function makeObjUsePlatformPaths (obj) {
  if (typeof obj === 'string') {
    …
  } else if (obj == null) {
    …
  } else {
    Object.keys(obj).forEach(function (key) {
      …
    })
  }
  return obj
}
```
Current node that is complete, but older versions you couldn't call `Object.keys` on things storing literals, eg:
```
var a = true
Object.keys(a) // TypeError: Object.keys called on non-object
var a = new Boolean(a)
Object.keys(a) // []
```
Now why this wouldn't fail w/o nyc, I can't guess? I would expect this to consistently fail on older nodes period.

**Comment by iarna** [comment]
And yeah, it does fail for me w/o nyc, so I think this is a false alarm.

**Comment by bcoe** [comment]
@iarna @othiym23 @addaleax, interesting, let's keep this open for a bit until we get npm green?

**Comment by addaleax** [comment]
Yep, pretty sure this is not related to nyc. There are [these objects](https://github.com/npm/npm/blob/785f3559717f989a3698ff64abb7ffab0026330d/test/tap/unit-gentlyrm.js#L347-L348) in the test file that look like `{ …, managed: false }`, which get passed to `makeObjUsePlatformPaths`. And that doesn’t work because `makeObjUsePlatformPaths` cannot handle booleans.

**Comment by othiym23** [comment]
Closing as not a problem with nyc. Thanks for your eyeballs, @addaleax, and thanks to all for taking a look!
