### ISSUE TITLE
--include prevents require hooks from executing on unmatched but required files

### ISSUE THREAD

**Issue by kirbysayshi** [bcoe/nyc#232]
If you have a project like:

```
lib/file1.js
lib/file2.js
shared-templates/tpl.hbs
tools/require-extensions/hbs.js
```

```js
// lib/file1.js
var template = require('../shared-templates/tpl.hbs');
console.log(template());
```

```js
// tools/require-extensions/hbs.js
var fs = require('fs');
var hbsfy = require('hbsfy');

require.extensions['.hbs'] = function (module, filename) {
  console.log('HBS!', filename);
  var file = fs.readFileSync(filename, "utf8");
  var opts = { traverse: true };
  return module._compile(hbsfy.compile(file, opts), filename);
}
```

And then run:

```
$ nyc --require ./tools/require-extensions/hbs.js --include ./lib/ node lib/file1.js
```

`./tools/require-extensions/hbs.js` will execute once, but the execution of `lib/file1.js` will fail (and no "HBS!" logs will be seen). The error will imply that node either couldn't load the `.hbs` file or something like `undefined is not a function` due to `template` being undefined.

But if one removes the `--include` flag, everything works as expected. I believe the include flag is  preventing require hooks from being applied to files that do not match the include pattern, even though they are required for the test to execute. This may be a strange edge case, as I'm guessing everyone assumed there would never be a file that nyc should not generate coverage for, but still needed a transform to allow tests to complete!

The use of the `--include` flag was originally because when using istanbul, if you don't specify an include it globs the entire directory, even traversing node_modules. When I switched to nyc I was very confused why hbs files weren't compiling anymore...

Not sure if this is a true bug, or just an addition that should be made to the documentation?

**Comment by kirbysayshi** [comment]
Also, another reason I was using the `--include` arg was because the project I'm working on has multiple entry points (views), but shared code between them. So we run tests+coverage for each entry point. The `--include` flag is an easy way of whitelisting the entry-point-specific code, without having to blacklist all the shared code.

**Comment by novemberborn** [comment]
@kirbysayshi any chance you could share a more complete setup? Perhaps in a repo?

nyc shouldn't even recognize the `.hbs` extension so I'm not sure how it would prevent any code execution.

**Comment by kirbysayshi** [comment]
@novemberborn I tried to reproduce this today with a new repo, and even tried with the internal code that initially prompted this report. nyc seems fine now! Not sure what I was doing wrong. Very sorry for the inconvenience of this bug report!
