### ISSUE TITLE
TypeError: Cannot read property '2' of undefined when avoiding require() cache

### ISSUE THREAD

**Issue by doque** [bcoe/nyc#235]
I have a module which has a conditional export:

```
import { merge } from 'lodash';

const numbers = {
    cars: {
        someNumber: 600,
        anotherNumber: 1440,
    },

    motorcycles: {
        someNumber: 200,
    }
};

module.exports = someConditional() ? numbers.cars : merge(numbers.cars, numbers.motorcycles);
```

Due to node's `require()` caching modules, I'm using [require-reload](https://www.npmjs.com/package/require-reload) to hot-reload the module for each of my tests, depending on a mocked `someConditional()`:

```
beforeEach(() => {
    sinon.stub(util, someConditional).returns(true);
    imageSizes = reload('../../src/imageSizes.js');
});
```

**This works fine for the tests, the module is reloaded and exports the appropriate json.**

However, it breaks the test coverage report, which yields this cryptic error:

```
__cov_XMVBS_cu$JTwIDoJGMvGhQ.s['1']++;var 
__cov_XMVBS_cu$JTwIDoJGMvGhQ=Function('return this')
();__cov_XMVBS_cu$JTwIDoJGMvGhQ.s['2']++;if(!__cov_XMVBS_cu$JTwIDoJGMvGhQ.__coverage__
){__cov_XMVBS_cu$JTwIDoJGMvGhQ.b['1']
[0]++;__cov_XMVBS_cu$JTwIDoJGMvGhQ.s['3']++;__cov_XMVBS_cu$JTwIDoJGMvGhQ.__coverage__={};}else{__cov_XMVBS_cu$JTwIDoJGMvGhQ.b['1']
[1]++;}__cov_XMVBS_cu$JTwIDoJGMvGhQ.s['4']++;__cov_XMVBS_cu$JTwIDoJGMvGhQ=__cov_XMV
BS_cu$JTwIDoJGMvGhQ.__coverage__;__cov_XMVBS_cu$JTwIDoJGMvGhQ.s['5']++;if(!__cov_XMVB
S_cu$JTwIDoJGMvGhQ['constants.js']){__cov_XMVBS_cu$JTwIDoJGMvGhQ.b['2']
[0]++;__cov_XMVBS_cu$JTwIDoJGMvGhQ.s['6']++;__cov_XMVBS_cu$JTwIDoJGMvGhQ['constants.js']
={'path':'/constants.js','s':{'1':0,'2':0,'3':0,'4':0,'5':0},'b':{'1':[0,0]},'f':{'1':0},'fnMap':{'1':
{'name':'someConditional','line':5,'


TypeError: Cannot read property '2' of undefined
    at Object.<anonymous> (constants.js:1:1)
```

**Comment by doque** [comment]
The error still occurs after removing the `require-reload` part entirely and importing the module just once.

**Comment by novemberborn** [comment]
Looks like Istanbul has trouble instrumenting the code. I've seen issues before with ternary operators and Istanbul before. Try placing `? numbers.cars` and `: merge…` on separate lines, that might help.

**Comment by doque** [comment]
I've pinpointed the issue - renaming the file from `constants.js` to `constants.jsx` solves the problem. Tests run through and reporting works. This is very strange. I've enabled both extensions in the package.json file.


I've also set up a git repo that demonstrates this bug: https://github.com/doque/break_coverage
Pleas note that any reference to `require-reload` or `_.merge` is gone, but the bug still persists.

**Comment by doque** [comment]
I've found the issue - adding `.js` as an extension breaks the reporting, like this:
```
"nyc": {
  "extension": [
    ".js",
    ".jsx"
  ]
}
```

This is due to the fact that the `.js` extension is always added by default: https://github.com/bcoe/nyc/blob/master/index.js#L59
So having the duplicate `.js` extension breaks the reporting.
