### ISSUE TITLE
Duplicate '.js' extension breaks coverage report

### ISSUE THREAD

**Issue by doque** [bcoe/nyc#236]
Like discussed in #235, adding the `.js` extension (either via command line or package.json) breaks the test coverage report, as it results in duplicate array elements.

I've set up a git repository to reproduce this bug here: https://github.com/doque/break_coverage.
You can switch between the branches to see that it works when removing the '.js' extension (or if you use my fork), see the README.

I realize this error can be attributed to the user, but feel like this should be avoided, which is why I've opened #237  that fixes this bug.

**Comment by bcoe** [comment]
@doque give this a spin:

`npm i nyc@next`

If it's doing the trick I'll promote the candidate release to `latest`.

**Comment by doque** [comment]
Works like a charm: https://github.com/doque/break_coverage

Thanks!
