### ISSUE TITLE
How to detect covered modules exit but not preloaded ones?

### ISSUE THREAD

**Issue by bahmutov** [bcoe/nyc#238]
Hi everyone,

I working on a tool called "liverage" that makes nyc coverage events a "live" stream that any client can connect to over a web socket. The goal is to make observing real time server coverage as simple as possible. The current setup that works is to load module `liverage` as a required one when running `nyc`. `liverage` installs mock global coverage object with setters and getters so that when `nyc` actually puts in a coverage object we are ready and can observe statement cover events without using obsolete `Object.observe`.

Typical usage

```
$ nyc --require liverage --reporter html node examples/basic/index.js
```

`liverage` creates a web socket server, but because the process never exits while the server is running, I don't know when to shut down the server. If I use `process.exit()` from my *client code* this does not work either because only sync operations can happen on Node process exit (like writeFileSync of the final code coverage results).

Do you have any idea how I can implement detecting when the instrumented client code finishes, but not the entire Node process? So far I see three choices (and all are suboptimal in my opinion)

- overriding `process.exit` myself and requiring the client code to use it
- using something like zones for the client code to detect when the client code is done
- starting the web server in a separate Node process and passing messages from the `nyc` process there to be sent to the observers

Any ideas would be welcome,

links: https://github.com/bahmutov/liverage

**Comment by novemberborn** [comment]
You should be able to [`unref()` your server](https://nodejs.org/api/net.html#net_server_unref). This "will allow the program to exit if this is the only active server in the event system." I haven't checked whether this is accessible in your web socket implementation.

Liverage seems neat! FYI I'm experimenting with replacing Istanbul for code coverage, and my approach would have streams bulit-in. See #217 for more. This is still a ways off though 😄

**Comment by bahmutov** [comment]
Thanks for the quick reply, yeah, I was looking at your Copenhagen module (as I was sitting in the namesake city working on liverage) and making the coverage a stream would be great and powerful feature.
