### ISSUE TITLE
nyc@6.4.2 broken in test that use mock-fs 

### ISSUE THREAD

**Issue by thangngoc89** [bcoe/nyc#246]
I reported this issue before and it was fixed (https://github.com/bcoe/nyc/issues/205).

But I noticed that in nyc@6.4.2, the issue comes back. It's fine with nyc@6.4.1

See build: https://travis-ci.org/MoOx/phenomic/jobs/127717652

**Comment by bcoe** [comment]
@thangngoc89 this should be fixed in `nyc@6.4.3`.

tldr; we need to figure out a better way to bundle dependencies.

**Comment by thangngoc89** [comment]
@bcoe Thanks a lot for this. Maybe you can use my test to detect this kind of issue

**Comment by bcoe** [comment]
@thangngoc89 did this fix things for you?

**Comment by thangngoc89** [comment]
@bcoe yes, it did
