### ISSUE TITLE
Support Q => mitigate istanbul and nyc both using coverage dir

### ISSUE THREAD

**Issue by ORESoftware** [bcoe/nyc#256]
Looks like NYC and Istanbul both write to the coverage dir - perhaps I should just use NYC only and not use Istanbul at all - but right now I am using both and they both write to the coverage directory.

Any recommendations on how to mitigate this? The problem I see is that when I run "nyc report --lcov-reporter" it will overwrite the previous report that may be from Istanbul.

**Comment by novemberborn** [comment]
You can use `--report-dir` to change the directory nyc writes its coverage report to.
