### ISSUE TITLE
Support sub directories for induvidual reporters

### ISSUE THREAD

**Issue by dlmr** [bcoe/nyc#258]
I would like to specify individual directories for each reporter and not just place everything under `--report-dir`. Would a PR that aims to add this functionality be accepted and if so is there any ideas on how that should be configurable?

One approach is to make it possible to specify several `--report-dir` just as you can with `--reporter` and each of them map in order to the reporter.

Or maybe this is possible today in some way?

**Comment by novemberborn** [comment]
> Or maybe this is possible today in some way?

You could call `nyc report` for each `--reporter`, specifying `--report-dir`.

**Comment by dlmr** [comment]
Thanks for the tip. Works great! 🙂

For some reason I thought that it would rerun my tests but I see that is not the case!
