### ISSUE TITLE
ES6 bug

### ISSUE THREAD

**Issue by jescalan** [bcoe/nyc#259]
So I'm not sure if this is on istanbul or nyc or someone else but figured I'd start here!

This code will produce uncovered lines as it is detected as a comment:

```js
if (foo === `/**`) {
  console.log('i am not covered?')
}
```

It seems like this has something to do with coverage not detecting backticks as a string

**Comment by jamestalmage** [comment]
@jescalan Can your provide more details? What test runner? How do you have it set up?

**Comment by jescalan** [comment]
Running tests with `ava`, set up without any sort of transpiling, running on node6 😁

**Comment by jamestalmage** [comment]
Is your code sample in a source file or AVA test file? I'm guessing the former.

If it is a source file and there is no transpiling happening, then this is almost certainly an `istanbul` issue. We only manipulate the coverage data if there is an inlined source-map (which there wouldn't be without transpiling).

**Comment by jescalan** [comment]
Yes, it's a source file. Ok so should I open this issue in istanbul then? Is the project still actively maintained?

**Comment by bcoe** [comment]
@jamestalmage my kingdom for a native ES6 plugin for nyc.

@jescalan open an issue on Istanbul; It's still relatively active, I'm also of the opinion that the nyc folks should start pitching in on it more 👍
