### ISSUE TITLE
fails when running `npm test`

### ISSUE THREAD

**Issue by mastilver** [bcoe/nyc#26]
Hi

I'm using nyc with mocha and coveralls
I've setup my .travis.yml and package.json as specified on the readme

The test is passing on travis and test coverage are send to coveralls.
But when I do `npm test` on my computer, it fails

```
> annotation-parser@2.5.2 test C:\perso\node-annotation-parser
> nyc mocha

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn mocha ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

The repo: https://github.com/mastilver/node-annotation-parser

**Comment by bcoe** [comment]
CC: @isaacs seems like our shebang logic is having trouble with Windows.

You might try explicitly specifying the path to the mocha bin:

`./node_modules/.bin/nyc ./node_modules/.bin/mocha test`

**Comment by mastilver** [comment]
I've set `test` by `./node_modules/.bin/nyc.cmd ./node_modules/.bin/mocha.cmd`

It's now outputting:

```
> sails-hook-annotation-router@0.1.1 test C:\perso\sails-hook-annotation-router
> nyc.cmd ./node_modules/.bin/mocha.cmd

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```

I've tested the same on linux, it does work.
Unfortunately I need to stick with windows for my job. :/

**Comment by isaacs** [comment]
Interesting!

I'm not super surprised that it doesn't work on Windows.  There's some deep and strange unixy stuff going on.  But I wonder where the error actually lies.

I'll try to spin up a VM soon.  Either spawn-wrap is just busted on Windows (my guess), or it's something specific to do with how nyc is invoking it.

**Comment by rmg** [comment]
I'm getting a failure on my Windows CI machines that might be related to this. The stack trace might be _slightly_ more useful than the above:
```
child_process.js:1162
    throw errnoException(err, 'spawn');
          ^
Error: spawn UNKNOWN
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at ChildProcess.spawn (D:\workspace\strongloop-license.pr\412f199f\node_modules\tap\node_modules\nyc\node_modules\spawn-wrap\index.js:143:18)
    at exports.spawn (child_process.js:995:9)
    at module.exports (D:\workspace\strongloop-license.pr\412f199f\node_modules\tap\node_modules\foreground-child\index.js:12:15)
    at Object.<anonymous> (D:\workspace\strongloop-license.pr\412f199f\node_modules\tap\node_modules\nyc\bin\nyc.js:54:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

That is the result of running `tap --bail --save fails.txt --coverage test/test-*.js` in a subshell that has `$(pwd)/node_modules/.bin` injected into the `PATH`.

**Comment by bcoe** [comment]
@rmg @mastilver I don't currently have a Windows testing environment, but I will try to get one up and running soon. It would be nice to try to get things at least partially working with Windows.

**Comment by motapc97** [comment]
For me, `nyc npm test` still fails on Windows, but now, I get another error.
I suspect it's because the `argv` variable is wrong, but I'm not sure...

![](http://i.imgur.com/hhhlhKa.png)

**Comment by rmg** [comment]
@motapc97 :-(

What about `nyc ./test/mota-test.js` or `nyc ./node_modules/.bin/grunt buildTest`?

**Comment by motapc97** [comment]
![](http://i.imgur.com/7hA9BBm.png)

As you can see, the first command doesn't fail, but I find no coverage output :(

**Comment by motapc97** [comment]
Sorry, but I keep getting errors...

![](http://i.imgur.com/L5HSvfA.png)
