### ISSUE TITLE
--all usage

### ISSUE THREAD

**Issue by jfcorugedo** [bcoe/nyc#262]
Hi.

First of all I'd like to thank you for your great job. This module is quite useful and usable.

My question has to do with `--all` parameter.

I want to know the real coverage of my project, taking into account those file never required. Unfortunately I've not been able to execute nyc using the --all option parameter.

When I execute this command:

    nyc --all --reporter=lcov --reporter=text --reporter=html npm run run-tests

I get the following error:

    Error: Line 1: Unexpected token
        at constructError (/Users/juanfernandez-corugedo/Documents/git/voting-client/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:2406:21)
        at createError (/Users/juanfernandez-corugedo/Documents/git/voting-client/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:2425:17)

I've also tried to execute that:

nyc --all=\"src/**\" --reporter=lcov --reporter=text --reporter=html npm run run-tests

It doesn't fail, but it ignores the --all flag.

Can you give me an example using this parameter?

**Comment by novemberborn** [comment]
You're usage is correct, however if you're using ES6 syntax nyc won't be able to instrument it. Judging by the error you may be running into that problem.

**Comment by JaKXz** [comment]
@jfcorugedo if you have the `babel-register` module in your project, this should work:
```
nyc --reporter=lcov --reporter=text --reporter=html --all --require babel-register npm run run-tests
```

**Comment by jfcorugedo** [comment]
Great! It works.

However, it includes some unexpected files:

     myProyect/coverage/                 |     5.56 |        0 |        0 |    15.58 |                |
      prettify.js                        |     4.32 |        0 |        0 |      100 |                |
      sorter.js                          |    13.75 |        0 |        0 |    14.47 |... 153,154,158 |
     myProyect/coverage/lcov-report/     |     5.56 |        0 |        0 |    15.58 |                |
      prettify.js                        |     4.32 |        0 |        0 |      100 |                |

I've not created those files (prettify.js and sorter.js). 

How can I tell coverage to include only files under `src` folder?

**Comment by JaKXz** [comment]
Specify an `include` block, as stated here: https://github.com/bcoe/nyc#including-files

**Comment by jfcorugedo** [comment]
Got it!

Now it works perfectly.

Thanks guys. Keep up the good work!
