### ISSUE TITLE
Odd coverage issue with async functions

### ISSUE THREAD

**Issue by reggi** [bcoe/nyc#270]
I have a mostly covered file except for some strange highlights on these async functions. 

Can anyone tell me whats going on here? Why is this file not covered 100%?

![screen shot 2016-06-09 at 8 07 16 pm](https://cloud.githubusercontent.com/assets/296798/15950546/de399c8a-2e7d-11e6-9524-7400685fe268.png)

![screen shot 2016-06-09 at 8 07 12 pm](https://cloud.githubusercontent.com/assets/296798/15950535/d5deb8b8-2e7d-11e6-9b93-1b7102f241f6.png)

![screen shot 2016-06-09 at 8 07 09 pm](https://cloud.githubusercontent.com/assets/296798/15950536/d5e220ca-2e7d-11e6-9a9a-2e04b5006d57.png)

![screen shot 2016-06-09 at 8 07 06 pm](https://cloud.githubusercontent.com/assets/296798/15950537/d5e68a5c-2e7d-11e6-9cea-17de3e9696dd.png)

![screen shot 2016-06-09 at 8 07 01 pm](https://cloud.githubusercontent.com/assets/296798/15950545/de396c60-2e7d-11e6-9a34-b0b25bce493e.png)

**Comment by JaKXz** [comment]
Hi @reggi thanks for your issue. This has been reported already in #265, and work is underway in #268. I'm going to close this in favour of those issues.
