### ISSUE TITLE
Expose `check-coverage` functionality

### ISSUE THREAD

**Issue by Raynos** [bcoe/nyc#28]
I was able to get `istanbul check-coverage` working using it's glob functionality

```sh
istanbul check-coverage --branches=100 --lines=100 --functions=100 '.nyc_output/*.json'
```

It would be nice if there was a `nyc check-coverage` command that did this for me and was documented with the `nyc` tool.

**Comment by bcoe** [comment]
:+1:

**Comment by bcoe** [comment]
@Raynos I've published this feature to the `next` tag on npm, give it a spin:

`npm install nyc@next`

If everything is looking good, I'll push things to `latest`.

https://github.com/bcoe/nyc/blob/master/CHANGELOG.md#v240-20150624-1557-0000
