### ISSUE TITLE
Generate coverage.json.

### ISSUE THREAD

**Issue by lijunle** [bcoe/nyc#283]
First, thank you for making such an awesome tool! With istanbul, there is a [coverage.json](https://github.com/gotwarlost/istanbul/blob/master/coverage.json.md) file, which can be used to report [partial line coverage](https://www.npmjs.com/package/codecov.io#advanced-partial-line-coverage). Could you please add such support?

**Comment by novemberborn** [comment]
@lijunle nyc uses istanbul's reporters. Use with `nyc --reporter=json npm test` or after running `nyc npm test` use `npm report --reporter=json`.
