### ISSUE TITLE
Allow specifying reporters with `nyc` directly

### ISSUE THREAD

**Issue by Raynos** [bcoe/nyc#29]
To get a report I currently run

```sh
nyc node test/index.js && nyc report --reporter text --reporter html
```

It would be great to just run

```sh
nyc node test/inedx.js --reporter text --reporter html
```

Also note I'm relying on the "--reporter" can appear multiple times feature which may be accidental :)

**Comment by bcoe** [comment]
@Raynos I love this idea. I will start looking into adding the option this week; it's not trivial because I need to be able to handle commands like:

`nyc ./node_modules/.bin/mocha --check-globals`, so I'll need to add some logic to intelligently munge `process.argv`.

**Comment by Raynos** [comment]
@bcoe 

The way istanbul does this is `nyc --reporter text --reporter html -- node test/index.js` 

It can also be handled like node where flags after `nyc` and before the binary belong to `nyc` and all other flags belong to the binary.

**Comment by bcoe** [comment]
@Raynos, I've got a testing branch that adds this support. I use `yargs` to parse `process.argv` and then I use the information I extract to slice the original arguments:

```js
NYC.prototype.mungeArgs = function (yargv) {
  return process.argv.slice(
    process.argv.indexOf(yargv._[0])
  )
}
```

Works great, but I'm waiting to land this pull, or something similar on one of the dependent libraries:

https://github.com/isaacs/foreground-child/pull/3

CC: @isaacs this was the feature request I was talking about, I think it's pretty cool.

**Comment by Raynos** [comment]
Nice work :) I'll try it out once it's ready. Thanks @bcoe appreciate it.
