### ISSUE TITLE
Report has bogus uncovered lines report

### ISSUE THREAD

**Issue by aredridel** [bcoe/nyc#35]
Files in `.nyc_output` are at https://gist.github.com/aredridel/67a635a727047e541c32

Output:

```
:; nyc report
------------|----------|----------|----------|----------|----------------|
File        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------|----------|----------|----------|----------|----------------|
 __root__/  |    94.92 |    81.13 |      100 |    94.92 |                |
  common.js |    94.37 |    69.23 |      100 |    94.37 | 94,146,150,154 |
  index.js  |    95.74 |    92.59 |      100 |    95.74 |          48,68 |
------------|----------|----------|----------|----------|----------------|
All files   |    94.92 |    81.13 |      100 |    94.92 |                |
------------|----------|----------|----------|----------|----------------|
```

**Comment by bcoe** [comment]
@aredridel are you running nyc on an open-source project? This could relate to a subprocess we're failing to cover, or a code path that's difficult to hit during the spawning process.

**Comment by aredridel** [comment]
Yeah, this is on https://github.com/aredridel/dust-makara-helpers/tree/browser-support

**Comment by aredridel** [comment]
Oh! That's not a number of uncovered lines. That's a list of them. Geez.

**Comment by aredridel** [comment]
I thought it was literally calculating 94 billion uncovered lines.

**Comment by aredridel** [comment]
Okay, this is not a bug. This is me misunderstanding the information in that column since it happened to parse as a number with thousands separators.

**Comment by bcoe** [comment]
@aredridel what do you think a better heading would be? a similar issue was here:

https://github.com/gotwarlost/istanbul/pull/390

we should be more clear!

**Comment by aredridel** [comment]
If there'd been spaces instead of commas it'd have been clear for me; not sure how that'd be interpreted internationally.

**Comment by aredridel** [comment]
"Which lines uncovered" would have made it clear too.

**Comment by willhayslett** [comment]
I know this is old, but I ran into this and was so confused. How about "Uncovered Line #'s" or "Uncovered Line Numbers"? "Uncovered Lines" isn't very clear.
