### ISSUE TITLE
I see coverage reports for my node_modules

### ISSUE THREAD

**Issue by sam-github** [bcoe/nyc#37]
The README suggests that this shouldn't happen.

I notice I see it for the only one of my deps that are npm linked into my project.

Its not a big deal, I can visually skip over it the parts I don't care of, but is this intended behaviour?

**Comment by bcoe** [comment]
@sam-github I've noticed this bug if I symlink files as well, I haven't had a chance to dig into the cause yet -- but seems like a legitimate bug.

**Comment by bcoe** [comment]
@sam-github could you try `nyc@5.0.0` and let me know if it solves this problem for you, we've rewritten the logic for excluding files -- it's now glob based.
