### ISSUE TITLE
What about my untested files?

### ISSUE THREAD

**Issue by ronkorving** [bcoe/nyc#39]
Hi,

So I tried out nyc on my project that I test with tape. I noticed that it doesn't report about files that are never touched by unit tests. Is this expected behavior? Everything looks very green, when in reality some files aren't yet tested at all.

**Comment by bcoe** [comment]
I think it would be a great enhancement to have nyc report %0 coverage on files that have not been executed.

**Comment by ronkorving** [comment]
Without it, I think it's very easy to lie to yourself.

**Comment by bcoe** [comment]
Let me know if you feel like taking a stab at this, otherwise I'll try to schedule some nyc hacking soon.

**Comment by ronkorving** [comment]
If you could leave some thoughts as to how this could be best accomplished in this project, I may find some time to give it a shot. I'm new to this code base, but never mind contributing when I have the time.

**Comment by rmg** [comment]
@ronkorving I think the simplest approach would be generating a list of files that are eligible for coverage and then adding stub entries for any that are missing in the final coverage report. Could be really prone to false-positives, though, depending on how the module is written.

**Comment by ronkorving** [comment]
I've opened https://github.com/gotwarlost/istanbul/issues/428 because the proper solution may be in Istanbul, rather than in nyc.

**Comment by bcoe** [comment]
@ronkorving I've landed `--all` on the `latest` release now.

I wanted to get some fixes in for Windows as well, and to do some further testing, before pushing the latest release.

Give `nyc@3.2.2` a shot, and let me know what you think.
