### ISSUE TITLE
Feature request: supress test output

### ISSUE THREAD

**Issue by ronkorving** [bcoe/nyc#40]
Running `nyc tape test/*.js`, I see the output of both the tests and the coverage report. When I run the coverage reporter, I'm not actually interested in the test output. It would be nice if there was an option like --silent for the test command itself, to suppress its output and only have the coverage report printed to my terminal.

**Comment by bcoe** [comment]
@ronkorving you should be able to pass the silent flag to nyc:

```
nyc --silent tape test/*.js
```

Does this work for you?

**Comment by ronkorving** [comment]
Not in front of a PC now but I tried that. Iirc it silences the coverage report, not the tape output.

**Comment by ronkorving** [comment]
Example output:

```
$ ./node_modules/.bin/nyc --silent ./node_modules/.bin/tape test/*.js
TAP version 13
# frame chunks
ok 1 Buffer count
ok 2 Byte count
# Download index.html
ok 3 spawned server
ok 4 connected
ok 5 200 OK
ok 6 contains HTML

1..6
# tests 6
# pass  6

# ok

$
```

I get no coverage report, but see my test output. The reverse of what I was hoping for.

**Comment by ronkorving** [comment]
When I remove --silent, the coverage report *is* shown, right after the test output.

**Comment by ronkorving** [comment]
So if you're saying --silent is *supposed* to silence the test, *not* the coverage report, please confirm that. I can make a PR to fix it.

**Comment by bcoe** [comment]
@ronkorving the purpose of `--silent` is to silent the coverage reporting. This is useful because people might want to simply output the coverage information to `nyc_output`, but not modify the test output itself. Does tape also accept a silent flag? If so this might work:

`nyc --silent tape test/*.js --silent`

**Comment by ronkorving** [comment]
There is no documented way in tape itself. I guess a devnull reporter could be made or otherwise, but from my user perspective, having a suppression flag in nyc would make sense as it would not be limited to tape. What do you think?

**Comment by bcoe** [comment]
@ronkorving perhaps an additional flag, `--really-silent` which would suppress all output, I think this would actually require an additional option flag in foreground-child:

https://github.com/isaacs/foreground-child

CC: @isaacs

**Comment by isaacs** [comment]
The goal of foreground-child (and, as far as I gather, of nyc) is to be identical to just running the command itself. This is why foreground-child always passes the parent stdio file descriptors to the child.  So, if tape doesn't have a way to suppress output, then I'd argue that nyc shouldn't suppress the output either.

You can do this, though, right?  `nyc --silent tape test/*.js &>/dev/null && nyc report`

If you run your tests with node-tap, you can do `-Rsilent` to use the 'silent' reporter, which doesn't output anything.

**Comment by bcoe** [comment]
this argument works for me, @ronkorving are you fine with piping to `/dev/null`?

**Comment by ronkorving** [comment]
Sure, if it's not as trivial to build in as I hoped, or if it doesn't fit the nyc philosophy, no problem.
