### ISSUE TITLE
documentation updates

### ISSUE THREAD

**Issue by bcoe** [bcoe/nyc#49]
Based on work we've been doing on wrap-ansi, there are a couple documentation updates we should make:

* point out that `nyc report` only works if you have already run tests inside the same project directory.
* point out that `COVERALLS_TOKEN` is optional if the repo is open-source (verify this to be the case).

CC: @sindresorhus, @Qix-

**Comment by sindresorhus** [comment]
Maybe also update the example here to include running tests in the `coverage` script https://github.com/bcoe/nyc#integrating-with-coveralls as it's a good default.

**Comment by bcoe** [comment]
I think the `COVERALLS_TOKEN` being optional is information that should live in the coveralls documentation. I've updated the example of piping coverage, which will land in this pull:

https://github.com/bcoe/nyc/pull/84

**Comment by sindresorhus** [comment]
It should, but you're pretty much telling everyone to waste time adding it when it's not needed in most cases:

> add the environment variable COVERALLS_REPO_TOKEN to travis, this is used by the coveralls bin.

If you're not going to document it, please remove that step.

**Comment by Qix-** [comment]
I'd go so far as to suggest it's a bit of a security risk as well by including the plain text coveralls token in a public repository's .travis file since they're intended for private repositories to begin with.

**Comment by sindresorhus** [comment]
@Qix- You can add it in the Travis web UI too.

**Comment by jamestalmage** [comment]
I don't understand what the coveralls environment variable enables on Travis. I've never used it. What am I missing out on?

**Comment by Qix-** [comment]
@Jamestalmage it's to validate yourself against coveralls when posting private repo coverage
