### ISSUE TITLE
coverage using exclude option

### ISSUE THREAD

**Issue by davidchase** [bcoe/nyc#50]
I am trying to use `nyc` with `ava` and running into a small issue for good measure here's a link to the conversation at [ava repo](https://github.com/sindresorhus/ava/issues/94).

So essentially i have a few directories in `node_modules` directory that i would like to cover since i do unit tests for them.

Unfortunately a setup like so:

```json
"config": {
    "nyc": {
      "exclude": [
        "node_modules/"
      ]
    }
  }
```

results in no coverage at all.

setting up more specific like `node_modules/utils` which are some of the files i need to cover results in a coverage containing too many files/packages such as `babel`, etc which i am not testing.

any suggestions on how to allow certain files from within `node_modules` directory?

thanks in advanced

**Comment by davidchase** [comment]
any interest in adding an `include` key

**Comment by bcoe** [comment]
@davidchase sorry for the slow reply, was on vacation and am just getting back in the swing of things.

I like the idea of an include key! do you want to take a stab at this? I don't think it would be too hard, just toggle the logic slightly when instrumenting files depending on whether an `exclude` or `include` option has been set when creating the nyc instance.

**Comment by davidchase** [comment]
@bcoe cool no worries added a PR #54

**Comment by bcoe** [comment]
@davidchase could you try `nyc@5.0.0`, we now have an `include` and `exclude` key, both of which use globs.
