### ISSUE TITLE
Babel Support?

### ISSUE THREAD

**Issue by shannonmoeller** [bcoe/nyc#53]
Is there a way to have `nyc` use `babel-istanbul` or `isparta` under the hood to support covering ES5+ code?

**Comment by bcoe** [comment]
@shannonmoeller I've been on my honeymoon, and am a bit slow on the open-source front these past couple weeks, so apologies!

Off the top of my head there isn't a way to do this, I love the idea however  -- I will need to dig into `babel-istanbul` and investigate how hard it would be to combine with `nyc`'s hijacking of the `istanbul` API.

**Comment by shannonmoeller** [comment]
@bcoe Congrats! No worries.

`babel-istanbul` and `isparta` are both forks of `istanbul` and share the same api. I've been playing around with a fork that adds an `--istanbul` flag that allows you to specify a custom module path. It's going fairly well, but still some bugs around the `check-coverage` command's execution of `foreground()`.

**Comment by shannonmoeller** [comment]
I've gotten to a point where my fork is using the correct version of `istanbul` as specified by the cli flag, but the way subprocesses are spawned isn't playing nice with `babel-node`:

```
./node_modules/.bin/babel-node ./node_modules/.bin/nyc -i babel-istanbul -r lcov -r text ./node_modules/.bin/tape test.js
```

**Comment by bcoe** [comment]
Hey @shannonmoeller this could be related to:

https://github.com/babel/babel/pull/3062

It would be awesome if you would chime in on that pull request, I'm trying to convince the maintainers of `babel` to open up a hook for tools that instrument babel compiled code.

**Comment by shannonmoeller** [comment]
I've chimed in there. That said, what I'd really love to see is instrumentation handled as a Babel plugin. That would deprecate the need for Istanbul to hook in at all and drop having to parse the code with both babel and esprima. But that's an issue for another repo.

**Comment by bcoe** [comment]
@shannonmoeller `nyc@4.x` is now out the door with Babel support. I've put together this blog post on the topic: https://github.com/polyglotweekly/polyglotweekly.com/pull/15

**Comment by shannonmoeller** [comment]
Thank you very much!
