### ISSUE TITLE
Normalize paths to posix before matching with `exclude` option

### ISSUE THREAD

**Issue by sindresorhus** [bcoe/nyc#56]
It's pretty awkward having to write a regex that supports both forward and backwards slashes.

https://github.com/jamestalmage/ava/blob/172f6d8f298351dc78ca9b06ffce26ba6a80d468/package.json#L81-L84
https://github.com/bcoe/nyc/blob/4e9545a0c039032585149bf503c797f975e1e982/index.js#L28

-

Ideally, `exclude` would just support globbing.

**Comment by bcoe** [comment]
:+1: I will try to get a release of nyc out within the next few days, I'm currently working on adding support for babel's require hook which has taken me down a bit of a refactoring rabbit hole.

**Comment by bcoe** [comment]
@sindresorhus well that took more days than I thought it would, sorry about that. when you have the time, could you give `nyc@5.0.0` a shot and let me know what you think of the new globbing functionality?

**Comment by sindresorhus** [comment]
Tried it out. Nice work!

In AVA, for our own tests, we use `nyc` indirectly through `tap`. Would it be possible to bump `nyc` in `tap` and do a new release?

**Comment by bcoe** [comment]
@sindresorhus I'll chat with @isaacs and see if we can work on upgrading, I'd love to move off of the fork of `spawn-wrap` potentially too.
