### ISSUE TITLE
When not using the require flag, nyc now breaks

### ISSUE THREAD

**Issue by mindmelting** [bcoe/nyc#61]
If not using the require flag, this line:
https://github.com/bcoe/nyc/blob/master/bin/nyc.js#L9
returns `[""]`
which when combined with this commit:
https://github.com/bcoe/nyc/commit/f33ac6dcec152439f35323fe31792031041780c7
breaks with this error:
```AssertionError: missing path```

I'll put together a PR to quickly fix...

**Comment by bcoe** [comment]
@mindmelting this should now be fixed in `nyc@4.0.1`, could you let me know if this does the trick for you?

**Comment by mindmelting** [comment]
Ha, looks exactly the same as my PR https://github.com/bcoe/nyc/pull/62 beat me to it!

Seems to bypass that issue, I am using nyc in combination with ava, and it hangs after running the tests, but I assume this may be a different issue Babel related... I'm investigating...

**Comment by mindmelting** [comment]
Yep works fine now, thanks!
