### ISSUE TITLE
Specify output folder

### ISSUE THREAD

**Issue by mateatslc** [bcoe/nyc#63]
Is there any way to control where it spits out the generated report without involving `.istanbul.yml`?

**Comment by jbcpollak** [comment]
+1

**Comment by azhang** [comment]
Seems like the code supports it, just need to add support for it in the cli:

https://github.com/bcoe/nyc/blob/master/index.js#L31

**Comment by jamestalmage** [comment]
I don't think we should go down the road of reimplementing every istanbul command line option. That adds a lot of overhead.

Is there a really good reason why this is needed? And why `.istanbul.yml` is such a bad choice?

**Comment by jbcpollak** [comment]
I just switched to using istanbul directly.

**Comment by jamestalmage** [comment]
> I just switched to using istanbul directly.

That's not a choice if your test runner forks processes (i.e. `tap` or `ava`). I would still be interested in the feedback

**Comment by jbcpollak** [comment]
Agreed. My recommendation would be to find a way to generically pass command line options through to Istanbul so you don't need to handle every one. It would also make nyc a more transparent wrapper.

**Comment by jamestalmage** [comment]
The problem there is that we actually do need to interfere with it a little bit (applying source-maps, collecting per-process info, etc).

**Comment by bcoe** [comment]
@jbcpollak @mateatslc @azhang I've made it so that the output directory can be configured with `--report-dir`, could you give the `next` tag of `nyc` a spin and see if it does the trick for you?

`npm i nyc@next`

**Comment by mateatslc** [comment]
@bcoe verified, works.
