### ISSUE TITLE
Ignoring code

### ISSUE THREAD

**Issue by ekmartin** [bcoe/nyc#67]
Hi! Are there any alternatives to `/* istanbul ignore next */` and [similar](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md)? Doesn't seem like the Istanbul variant is taken into consideration at least.

**Comment by kolodny** [comment]
+1

**Comment by jamestalmage** [comment]
We use istanbul under the covers, so I am surprised to hear istanbul comments don't work. Can you submit a minimal reproduction?

**Comment by kolodny** [comment]
@jamestalmage here you go https://gist.github.com/kolodny/8bc9d82cf0f147161a9a

**Comment by jamestalmage** [comment]
If I had to guess, it would be that the babel transform is the problem. Does it work if you do not bring babel in the mix?

**Comment by kolodny** [comment]
I think so, so does that make this a babel sourcemaps bug or a nyc edge
case not accounted for?

**Comment by jamestalmage** [comment]
not sure yet.

**Comment by jamestalmage** [comment]
investigating now

**Comment by jamestalmage** [comment]
confirmed: https://github.com/jamestalmage/__nyc-coverage-issue-67

@novemberborn - The only way to get the coverage report to show 100% like it should is to manually transform **without** source-maps. The transforms aren't getting in the way here. There is a bug. You are way deeper in to source-map support than I am, so I'm punting to you.

**Comment by novemberborn** [comment]
@jamestalmage my guess is that the original coverage has done what it does to mark the ignored code as covered. But then the source map is applied and that somehow gets lost. I'll see about hooking in [`remap-istanbul`](https://github.com/SitePen/remap-istanbul) purely for the remapping, perhaps they've already taken this into account.

**Comment by novemberborn** [comment]
@ekmartin @kolodny #92 should fix this. If you could install that branch to confirm that would be appreciated. Thanks! :smile:

**Comment by ekmartin** [comment]
That worked @novemberborn, thanks :smiley:.

**Comment by kentcdodds** [comment]
Hi there, this doesn't seem to be working for me. Here's an example of what I've got:

```javascript
// Foo.js
import wrap from './Wrap'

export function foo() {
  return 'bar'
}

/* istanbul ignore next */
export default wrap(() => {})(foo)



// Wrap.js
export default function wrap() {
  return function() {
  }
}




// Foo.test.js
import test from 'ava'
import { foo } from './Foo'

test('foo', t => {
  t.same(foo(), 'bar')
})
```

Resulting coverage:

<img width="581" alt="screen shot 2016-01-26 at 10 22 23 am" src="https://cloud.githubusercontent.com/assets/1500684/12588605/b66622b8-c416-11e5-81f9-886553b66546.png">

Should I file a separate issue for this or am I doing something wrong?

**Comment by kentcdodds** [comment]
Also, if it's helpful. Here's the [transpiled code](http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=import%20wrap%20from%20'.%2FWrap'%0A%20%0Aexport%20function%20foo()%20%7B%0A%20%20return%20'bar'%0A%7D%0A%20%0A%2F*%20istanbul%20ignore%20next%20*%2F%0Aexport%20default%20wrap(()%20%3D%3E%20%7B%7D)(foo)%0A%20%0A%20%0A):

```javascript
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
exports.foo = foo;

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _Wrap = require('./Wrap');

var _Wrap2 = _interopRequireDefault(_Wrap);

function foo() {
  return 'bar';
}

/* istanbul ignore next */
exports['default'] = (0, _Wrap2['default'])(function () {})(foo);
```

I believe that should work. I also tried [this](http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=import%20wrap%20from%20'.%2FWrap'%0A%20%0Aexport%20function%20foo()%20%7B%0A%20%20return%20'bar'%0A%7D%0A%20%0Aexport%20default%20wrap(%2F*%20istanbul%20ignore%20next%20*%2F()%20%3D%3E%20%7B%7D)(foo)%0A%20%0A%20%0A):

```javascript
import wrap from './Wrap'
 
export function foo() {
  return 'bar'
}
 
export default wrap(/* istanbul ignore next */() => {})(foo)
```

But that didn't appear to make a difference.

**Comment by kentcdodds** [comment]
I should mention that I'm using the latest version of nyc.

**Comment by novemberborn** [comment]
@kentcdodds I've managed to reproduce this. Looks like the source map code wasn't preserving skip annotations for entire functions, just for code locations. Will have a PR shortly.

**Comment by novemberborn** [comment]
@kentcdodds could you try with https://github.com/bcoe/nyc/pull/159?

**Comment by bcoe** [comment]
@kentcdodds @ekmartin @kolodny, could you give the following a shot:

`npm i nyc@next`

If this does the trick for you, I'll promote `5.6.0` to latest sometime tomorrow.

**Comment by kentcdodds** [comment]
Works for me :+1:
