### ISSUE TITLE
--all option fails with ES6 modules

### ISSUE THREAD

**Issue by jwhitfieldseed** [bcoe/nyc#91]
`--all` causes NYC to fail immediately for code with ES6 modules. I am using Node @5.1.0, nyc @5.0.0 with `mocha` and `babel-register`.

The error looks like:

```
/Users/joe/code/nyc-all-issue/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:5703
            throw e;
                  ^
Error: Line 1: Unexpected token
    at constructError (/Users/joe/code/nyc-all-issue/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:2405:21)
    at createError (/Users/joe/code/nyc-all-issue/node_modules/nyc/node_modules/istanbul/node_modules/esprima/esprima.js:2424:17)
...
```

__.babelrc__:

```
{
  presets: ["es2015"]
}
```

__package.json__:
```
{
  "scripts": {
    "test": "nyc --require babel-register mocha test.js",
    "test-all": "nyc --require babel-register --all mocha test.js",
    "run": "node test.js"
  },
  "dependencies": {
    "babel-core": "^6.3.17",
    "babel-preset-es2015": "^6.3.13",
    "babel-register": "^6.3.13",
    "mocha": "^2.3.4",
    "nyc": "^5.0.0"
  }
}
```

`$ npm test` succeeds and `$ npm run test-all` fails where `test.js` uses `import`, or `requires` a file that uses `import`. 

https://github.com/jwhitfieldseed/nyc-issue-91 reproduces. It runs NYC with/out `--all` on code with/out `import`. 

It seems other syntax that needs transpiling is OK with or without `--all`. I tested with rest args, which are not in Node 5.

__with import__
```
$ npm run test       // success
$ npm run test-all   // fails unexpectedly
$ npm run run        // SyntaxError, as expected - no rest args or import in Node 5
```

__without import__
```
$ npm run test       // success
$ npm run test-all   // success
$ npm run run        // SyntaxError, as expected - no rest args in Node 5
```

**Comment by novemberborn** [comment]
Ohh nice find!

`--all` bypasses any custom require hooks loaded through `--require`, so the files are never transpiled before being handed to Istanbul, which then fails to parse the new syntax.

@bcoe is there any insight you could provide as to `--all`'s implementation? It seems to run in the topmost `nyc` process, not in the `mocha` subprocess, so simply doing a `require(filename)` inside `addAllFiles()` doesn't work either.

**Comment by bcoe** [comment]
@novemberborn @jwhitfieldseed I know Istanbul has its own implementation of this functionality using the configuration setting: `--include-all-sources`, perhaps we could see about having this functionality exposed when running Istanbul as an API? I'm not quite sure what this would entail CC: @gotwarlost

**Comment by albertogasparin** [comment]
I can confirm this bug: `--all` + `--require` = :boom: 
Tried setting `include-all-sources: true` in `.istanbul.yml`, but it does nothing.

**Comment by bcoe** [comment]
@albertogasparin mind sending a gist or link to a project with a minimal failing example, I'm on the road for 8 hours today and would love to work on patching this.

**Comment by jwhitfieldseed** [comment]
@bcoe is the repo from the issue useful? `npm test` fails in https://github.com/jwhitfieldseed/nyc-issue-91/tree/master/with-import.

**Comment by jwhitfieldseed** [comment]
@bcoe actually, removing some indirection:

    cd with-import
    ./node_modules/.bin/nyc --require babel-register --all mocha index.js

**Comment by bcoe** [comment]
@jwhitfieldseed :+1: that' a big help.

**Comment by cantidio** [comment]
Hello @bcoe I see that you closed this issue, but this still seems to be happening. Do we have a workaround? thanks
