### ISSUE TITLE
babel support broken on master

### ISSUE THREAD

**Issue by bcoe** [bcoe/nyc#94]
there was a regression with the most recent patches that landed on master:

<img width="587" alt="screen shot 2015-12-14 at 9 20 22 pm" src="https://cloud.githubusercontent.com/assets/194609/11802718/b047a508-a2a8-11e5-8720-7c35a63da3f8.png">

EDIT: looks like the remapping branch hasn't landed yet -- nothing is immediately jumping out at me as to why this is now cropping up.

```sh
.//node_modules/babel-cli/node_modules/convert-source-map/index.js:  // //# sourceMappingURL=foo.js.map                       /*# sourceMappingURL=foo.js.map */
```

Leading to:

```sh
[Error: An error occurred while trying to read the map file at /Users/benjamincoe/bcoe/yarsay/node_modules/babel-core/node_modules/convert-source-map/foo.js.map
```

## Reproducing

This issue can be reproduced by running tests on this library:

https://github.com/bcoe/yarsay

CC: @novemberborn, @jamestalmage

**Comment by jamestalmage** [comment]
It works for me on Node 5.2, but not Node 4. Which is odd.

**Comment by jamestalmage** [comment]
This is related to Babel not playing nice with extensions. The fix for that is in the works, but we should probably revert out the appendTransform stuff until that happens.

**Comment by jamestalmage** [comment]
Found it!

Pretty major oversight in my tests for `append-transform`. I never tried transforms that were once removed (i.e. requiring a module that required a module that was transformed). Fix is released in `append-transform@0.2.1`.

I'm having a hang of a time getting `yarsay` to work using npm link though. Instead I was able to get it to work by packing up a tarball and installing that:

```
$ cd ~/dev/nyc
$ npm pack
$ cd ../yarsay
$ npm i -D ../nyc/nyc-5.0.1.tgz
$ npm i
$ npm test
```

I *think* the reason this works better `npm link` is that it does not bring along `nyc`s dev-dependencies.  It looked to me like the wrong version of Babel was getting required (the one inside `node_modules/nyc/node_modules`).

**Comment by novemberborn** [comment]
> I think the reason this works better npm link is that it does not bring along nycs dev-dependencies. It looked to me like the wrong version of Babel was getting required (the one inside node_modules/nyc/node_modules).

Hmm that seems reasonable. Note that nyc doesn't depend on Babel anymore, it must be a transitive dependency showing up at a higher level due to flattening.

**Comment by jamestalmage** [comment]
yes - I think that is what is happening. Either way, #98 makes `npm link` "just work".

**Comment by jamestalmage** [comment]
@bcoe - I think this issue is now fixed on master. Can you verify?

**Comment by bcoe** [comment]
:+1: this week has been slammed at npm, but I plan on an open-source heavy weekend. You have some awesome write ups in other tickets I'd like to give feedback on too.
